com.unity.probuilder/Runtime/Core/Face.cs

https://unity3d.atlassian.net/browse/WB-1199

Fix texture groups being lost on duplicate

---

com.unity.probuilder/Runtime/Core/Vertex.cs
com.unity.probuilder/Runtime/MeshOperations/CSG/Classes/CSG_Model.cs
com.unity.probuilder/Runtime/MeshOperations/CSG/Classes/CSG_Node.cs
com.unity.probuilder/Runtime/MeshOperations/CSG/Classes/CSG_Plane.cs
com.unity.probuilder/Runtime/MeshOperations/CSG/Classes/CSG_Vertex.cs
com.unity.probuilder/Runtime/MeshOperations/CSG/Classes/CSG_VertexUtility.cs
com.unity.probuilder/Runtime/MeshOperations/CSG/Classes/CSG_VertexUtility.cs.meta

https://fogbugz.unity3d.com/f/cases/1059817/

Fix boolean tool expecting certain mesh attributes to be present

---

com.unity.probuilder/Editor/EditorCore/UVEditor.cs

Fixes issue https://unity3d.atlassian.net/browse/WB-1047

Fix undo not refreshing the UV editor graph

---

com.unity.probuilder/Editor/EditorCore/Lightmapping.cs

- Don't expect PropertyModifications to be valid in undo post-process

Fix null-ref when assigning material key in Timeline

---

com.unity.probuilder/Runtime/MeshOperations/InternalMeshUtility.cs

Fixes a bug that prevented projects from building.

Remove reference to Selection in runtime code

---

com.unity.probuilder/Editor/EditorCore/EditorGUIUtility.cs
com.unity.probuilder/Editor/EditorCore/UVEditor.cs

Increase min width of UV inspector to disallow horizontal scrollbar

---

com.unity.probuilder/Editor/MenuActions/Geometry/ConnectEdges.cs

if connection count was 0 the connection code would invalidate selection

fixed losing selection when connecting invalid edges

---

com.unity.probuilder/Editor/EditorCore/UVEditor.cs

Fix this case: https://unity3d.atlassian.net/browse/WB-1306

Always enable scrollbar in UV Editor actions window.

---

com.unity.probuilder/Editor/EditorCore/EntityVisibility.cs
com.unity.probuilder/Runtime/Core/ColliderBehaviour.cs
com.unity.probuilder/Runtime/Core/EntityBehaviour.cs
com.unity.probuilder/Runtime/Core/TriggerBehaviour.cs

rendering was disabled onEnterPlayMode, which was not valid if user was loading scenes from code.
Added logic to onSceneLoaded for the same effect. Also made sure renderer hideflags was turned off in builds.

fixed colliders and triggers debug display

---

com.unity.probuilder/Runtime/MeshOperations/UV/UvUnwrapping.cs

Rotation and scale is now down before applying the anchor

Changed the order of UV transform operation

---

com.unity.probuilder/Runtime/Core/Projection.cs

Noticeably, when faces are grouped this would flip the projection axis.
https://unity3d.atlassian.net/browse/WB-1081

Fix PlanarProject using incorrect projection normal

---

com.unity.probuilder/Editor/EditorCore/ProBuilderMeshEditor.cs

https://unity3d.atlassian.net/browse/WB-1339

add "open probuilder" button back to ProBuilderMesh inspector

---

com.unity.probuilder/Editor/EditorCore/Pref.cs
com.unity.probuilder/Editor/EditorCore/UnityScenePostProcessor.cs

Fixes the `Script Stripping` option not being respected when building.

Fix PostSceneProcessor not removing `ProBuilderMesh`component

---

com.unity.probuilder/Runtime/Core/Normals.cs

Fix exception in Normals class when vertex count exceeds ushort.max

Fix plane creation tool potential exception

---

com.unity.probuilder/Editor/EditorCore/BooleanEditor.cs

Fix boolean editor window not resizing preview fields with layout

---

com.unity.probuilder/Editor/EditorCore/ReflectionUtility.cs

- Addresses a potential null reference exception (noted in FB case 1137080, but not reproduced)

Guard against potential NRE in ReflectionUtility

---

com.unity.probuilder/Editor/EditorCore/EditorUtility.cs
com.unity.probuilder/Editor/EditorCore/ShapeEditor.cs

Fixes shapes not instantiating in the prefab stage.
https://unity3d.atlassian.net/browse/WB-792
Fogbugz: 1093351

Fix shape instantiation in prefab scene

---

com.unity.probuilder/Editor/EditorCore/MeshSelection.cs
com.unity.probuilder/Runtime/Core/ProBuilderMesh.cs
com.unity.probuilder/Runtime/Core/ProBuilderMeshFunction.cs

Fixes an error when exporting assets in place.

Fix null reference error if mesh component is removed without modifying selection

---

LICENSE.md

Request from doc team: set license year to 2019.

Update year indication in license file.

---

Content/Shader/PointBillboard.shader

Fixes an issue where vertices would render slightly more offset from their actual position as they get farther from the center of the camera frustum.

Fix offset vertices when scene is orthographic on cardinal axis

---

Editor/EditorCore/EditorSceneViewPicker.cs
Settings/Editor/UserSettingsProvider.cs

Fix edge hover taking hidden edges in some cases

---

Editor/EditorCore/PolyShapeEditor.cs

- WB-1490 (fix poly shape not resetting SelectMode when undo-ing enter shape mode)
- WB-1484 (revert shape preview while in path edit mode)

Poly Shape Editor Fixes

---

Editor/EditorCore/MaterialEditor.cs
Editor/EditorCore/UndoUtility.cs

Fix apply material not registering MeshRenderer for undo

---

Editor/EditorCore/PolyShapeEditor.cs
Runtime/MeshOperations/AppendElements.cs
Tests/Runtime/MeshOps/AppendElementsTests.cs
Tests/Runtime/MeshOps/AppendElementsTests.cs.meta

If there is extrusion the other faces will be created otherwise it will remain single sided.

Wb 152 allow zero height polyshape

---

Editor/EditorCore/BooleanEditor.cs
Editor/EditorCore/Experimental.cs

https://fogbugz.unity3d.com/f/cases/1167692/

Fix boolean menu not respecting the Experimental Features Enabled pref

---

Runtime/MeshOperations/AppendElements.cs
Runtime/MeshOperations/Triangulation.cs
Tests/Runtime/MeshOps/AppendElementsTests.cs

Added scripting support for creating polygons with holes in them using Poly2Tri's support for it.
This is my first pull request so feedback is very welcome.

Added hole support to creating shapes from a polygon.

---

Editor/MenuActions/Selection/SelectMaterial.cs
Tests/Editor/Selection/SelectMaterial.cs
Tests/Editor/Selection/SelectMaterial.cs.meta

Select by material was selecting by material index rather than by material. This change address this issue.

Wb 1398 select by material

---

Editor/EditorCore/EditorGUIUtility.cs
Editor/MenuActions/Geometry/SubdivideEdges.cs

New widget allowing a min max range + editable UI range. As per Gabriel request there is no automatic expansion of the range setting section.

Wb 1056 edge subdivision ui

---

Editor/EditorCore/ProBuilderEditor.cs

Request by @gabrielw-us 
https://unity3d.atlassian.net/browse/WB-1699

Changed the Picking Distance

---

Editor/EditorCore/PreferencesUpdater.cs

Fixes warnings introduced in this PR https://github.com/Unity-Technologies/com.unity.probuilder/pull/212

fix warnings about deprecated api for prefs

---

Editor/EditorCore/MeshSelection.cs

https://fogbugz.unity3d.com/f/cases/1196964/

fix null-ref when undo/redo add or remove pbmesh components

---

Editor/EditorCore/PolyShapeEditor.cs

https://fogbugz.unity3d.com/f/cases/1198138/

esc always exits to no edit mode, never deletes object

---

Content/Shader/LineBillboard.shader
Content/Shader/PointBillboard.shader

Backports https://github.com/Unity-Technologies/com.unity.probuilder/pull/219

Backport shader warning fix

---

.yamato/promotion.yml
.yamato/upm-ci.yml

**Goal of this PR**:
Convert jobs with no commands to virtual jobs, as required.

CI - Convert certain jobs to virtual jobs.

---

Editor/EditorCore/SmoothGroupEditor.cs

Fix this case: https://fogbugz.unity3d.com/f/cases/1183101

Update documentation link in Smoothing panel

---

Editor/EditorCore/UVEditor.cs

Fix this case: https://fogbugz.unity3d.com/f/cases/1204088

UVEditor, prevent higlight in Vertex/Face mode while dragging the Actions window

---

Runtime/Core/ProBuilderMesh.cs

Fix this case: https://fogbugz.unity3d.com/f/cases/1198588

Check for null before invalidating faces.

---

Runtime/MeshOperations/Bevel.cs

https://fogbugz.unity3d.com/f/cases/1194858/
beveled gemoetry is still off though

fixed null ref on bevel

---

Editor/EditorCore/PolyShapeEditor.cs
Editor/EditorCore/ProBuilderEditor.cs

[[case#1203685]](https://fogbugz.unity3d.com/f/cases/1203685/)
Repro Steps:
- Turn off gizmos using the Scene View's Gizmo Toggle
- Try creating/editing a PolyShape

Fixed Polyshape Not Working When Gizmos Are Off

---

Editor/EditorCore/TooltipEditor.cs

Fix this case: https://fogbugz.unity3d.com/f/cases/1211096

Tooltip: make sure its window stays in screen width

---

Editor/MenuActions/Export/Export.cs

https://fogbugz.unity3d.com/f/cases/1201858/

fixed message notification on export

---

Runtime/Core/ProBuilderMeshFunction.cs
Samples~/Editor/CreateShadowObject.cs

https://fogbugz.unity3d.com/f/cases/resolve/1211169/

make sure mesh is created before copying

---

CHANGELOG.md
Editor/EditorCore/AutoUVEditor.cs
Editor/EditorCore/UVEditor.cs
package.json

https://fogbugz.unity3d.com/f/cases/1210096/

fixed rotation clamping

---

CHANGELOG.md
Editor/MenuActions/Object/ProBuilderize.cs

Fixes an issue where the toolbar layoutting could throw an error if ProBuilderize action utilizes a progress bar.
https://fogbugz.unity3d.com/f/cases/1195261/

Fix probuilderize layout error

---

CHANGELOG.md
Editor/MenuActions/Object/ProBuilderize.cs

Reverts Unity-Technologies/com.unity.probuilder#256

Revert "Fix probuilderize layout error"

---

CHANGELOG.md
Editor/EditorCore/EditorSceneViewPicker.cs

https://fogbugz.unity3d.com/f/cases/1217024/

Fix inverted picking bias when cursor is not hovering selected object

---

CHANGELOG.md
Runtime/Core/ProBuilderMesh.cs
Runtime/Core/ProBuilderMeshFunction.cs

Case: [#1217930](https://fogbugz.unity3d.com/f/cases/1217930/)

Fixed duplicated objects shape reverts to original's mesh when entering Play mode

---

CHANGELOG.md
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/PolyShapeEditor.cs
Editor/EditorCore/ShapeEditor.cs
Editor/MenuActions/Editors/NewPolyShape.cs
package.json

https://fogbugz.unity3d.com/f/cases/1221121/

Fix Poly Shape Undo Crash

---

CHANGELOG.md
Editor/EditorCore/ShapeEditor.cs
package.json

backports https://github.com/Unity-Technologies/com.unity.probuilder/pull/259

Fix shapebuilder prefs

---

CHANGELOG.md
Editor/EditorCore/ShapeEditor.cs

https://forum.unity.com/threads/probuilder-shape-tool-settings-saved-where.828690/

fix shape editor prefs not registering for reset

---

CHANGELOG.md
Editor/EditorCore/UnwrapParametersEditor.cs
Runtime/Core/ProBuilderMeshFunction.cs

https://fogbugz.unity3d.com/f/cases/1158748/

Fix export and strip scripts leaving meshfilter hidden

---

Editor/EditorCore/ShapeEditor.cs

[[case #1224413]](https://fogbugz.unity3d.com/f/cases/1224413/)

Fixed preview object reappearing if shape editor is closed in play mode

---

CHANGELOG.md
Editor/EditorCore/UVEditor.cs
Editor/EditorCore/UVRenderOptions.cs

https://fogbugz.unity3d.com/f/cases/1225427/

Fix the UV template rendering offset when editor is not a utility window

---

CHANGELOG.md
Editor/EditorCore/ShapeEditor.cs

https://fogbugz.unity3d.com/f/cases/1228271/

Fix cylinder shape clamping radius value to .001

---

CHANGELOG.md
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/HierarchyListener.cs
Editor/EditorCore/ProBuilderMeshEditor.cs
Editor/EditorCore/UnityScenePostProcessor.cs
Runtime/Core/ProBuilderMesh.cs
Runtime/Core/ProBuilderMeshFunction.cs

https://fogbugz.unity3d.com/f/cases/1225223/

fix mesh colliders not having sharedmesh property populated in builds

---

CHANGELOG.md
Runtime/Core/Bounds2D.cs

Check for empty enumerable before accessing it
https://fogbugz.unity3d.com/f/cases/1238115/

check for empty enumerable

---

CHANGELOG.md
Editor/MenuActions/Selection/SelectEdgeLoop.cs
Runtime/MeshOperations/ElementSelection.cs

Added iterative selection for edges loop
**Fogbugz:**
**Jira:**

Iterative edge loop

---

Editor/MenuActions/Selection/SelectEdgeLoop.cs
Editor/MenuActions/Selection/SelectEdgeRing.cs
Runtime/MeshOperations/ElementSelection.cs

Added iterative edge ring selection option

Iterative edge ring

---

.yamato/promotion.yml
.yamato/upm-ci.yml

[Brief summary of the changes in this PR.]
**Fogbugz:**
**Jira:**

update mac images

---

CHANGELOG.md
Editor/MenuActions/Selection/SelectEdgeLoop.cs
Runtime/MeshOperations/ElementSelection.cs

Fixes https://fogbugz.unity3d.com/f/cases/1241105/

fix edge case in get spokes function

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditor.cs

Fixed Shift selection being inconsistent
https://fogbugz.unity3d.com/f/cases/1249056/

Fix ctrl select

---

CHANGELOG.md
Editor/EditorCore/MeshAndElementSelection.cs

Fixed Shift selection being inconsistent
https://fogbugz.unity3d.com/f/cases/1249071/
There is the same issue with edges and vertexes, so if the code for the PR is okay I will fix the other 2 in this same PR.
EDIT: Added code to fix vertexes and edges as well. Pretty much the same as with faces.

Fix shift select

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditor.cs
Editor/EditorCore/ShapeEditor.cs
Runtime/Core/ProBuilderMeshFunction.cs

- [don't throw errors when entering prefab stage with appended geometry](https://fogbugz.unity3d.com/f/cases/1247270/)
- [fix 48 side limit for cylinder](https://forum.unity.com/threads/probuilder-deletes-faces-when-subdividing-edges.912122/#post-5986616)

Bug Week Small Fixes

---

CHANGELOG.md
Editor/EditorCore/EditorMeshHandles.cs
Editor/EditorCore/EditorSceneViewPicker.cs
Editor/EditorCore/ProBuilderEditor.cs
Editor/MenuActions/Selection/SelectPathFaces.cs
Runtime/Core/SelectionPickerSettings.cs

Added a preview for the pathfinding functionality on faces. When holding shift+ctrl, faces that would be selected should be highlighted.

Feature preview pathfinding

---

CHANGELOG.md
package.json

Update to Settings Manager 1.0.3
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1266811/

update to settings manager 1.0.3

---

CHANGELOG.md
Editor/EditorCore/UnityScenePostProcessor.cs
package.json

backports a fix from 5.0.0 when stripping bezier shapes during build time
https://fogbugz.unity3d.com/f/cases/1286720/

V4.4/strip bezier fix

---

CHANGELOG.md
Editor/EditorCore/CutTool.cs
Editor/EditorCore/PolyShapeTool.cs
Editor/EditorCore/ProBuilderEditor.cs
Editor/MenuActions/Editors/NewPolyShapeToggle.cs
Editor/MenuActions/Object/FreezeTransform.cs
Samples~/Editor.meta
Samples~/HDRP.meta
Samples~/Runtime.meta
Samples~/Runtime/Icosphere FFT/Audio Visualizer.unity
Samples~/UniversalRenderPipeline.meta

Collection of bugfixes raised by PB 5.0 preview release
Fixes for various bugs identified on the preview of PB 5.0
**Fogbugz:** 
https://fogbugz.unity3d.com/f/cases/1296422/
https://fogbugz.unity3d.com/f/cases/1296427/
https://fogbugz.unity3d.com/f/cases/1296428/
https://fogbugz.unity3d.com/f/cases/1296494/
https://fogbugz.unity3d.com/f/cases/1296104/

PB 5.0 bugfix collection

---

CHANGELOG.md
package.json

Fix missing dependency to physics module 
**Fogbugz:** [case#1299638](https://fogbugz.unity3d.com/f/cases/1299638/)

Added the physics module as a dependency

---

CHANGELOG.md
Content/Shader/ScrollHighlight.shader

Backport of this PR: https://github.com/Unity-Technologies/com.unity.probuilder/pull/343

[Backport] Fixed shader warning in URP for UNITY_PASS_FORWARDBASE redefinition

---

CHANGELOG.md
Runtime/Core/SelectionPickerRendererStandard.cs

Backport of this PR: https://github.com/Unity-Technologies/com.unity.probuilder/pull/340
More specifically this commit: https://github.com/Unity-Technologies/com.unity.probuilder/pull/340/commits/e9b82a44778ee5d1786893dae13b17e144da67b1 without the change to `Smoothing.cs`

[Backport] Fix Rect Selection in URP

---

Editor/EditorCore/EditorToolbarMenuItems.cs
Editor/MenuActions/Editors/NewBezierShape.cs
Editor/MenuActions/Editors/NewPolyShapeToggle.cs
Editor/MenuActions/Editors/NewShapeToggle.cs

Re-adding menu entry for the new shape tool.
The menu entry was not present anymore, I re-added it in that PR.

Re-adding menu entry for the new shape tool

---

CHANGELOG.md
package.json

V4.5/4.5.2

---

CHANGELOG.md
Debug/Editor/MeshInfo.cs
Editor/EditorCore/CutTool.cs
Editor/EditorCore/DrawShapeTool.cs
Editor/EditorCore/EditShapeTool.cs
Editor/EditorCore/HierarchyListener.cs
Editor/EditorCore/Lightmapping.cs
Editor/EditorCore/MeshDebugTool.cs
Editor/EditorCore/MeshDebugTool.cs.meta
Editor/EditorCore/PolyShapeTool.cs
Editor/EditorCore/ProBuilderShapeEditor.cs
Editor/EditorCore/RepairActions.cs
Runtime/Core/Math.cs
Runtime/Core/MeshUtility.cs
Runtime/Core/Normals.cs
Runtime/Core/ProBuilderMesh.cs
Runtime/Core/ProBuilderMeshFunction.cs
Runtime/Core/Projection.cs
Runtime/Core/ShapeGenerator.cs
Runtime/MeshOperations/MeshValidation.cs
Runtime/Shapes/Cylinder.cs

- Fixed issue where instantiating a prefab would not build UV2s.
- Additional instructions in the missing UV2 warning log.
- Fix some styling issues with Overlays in 21.2
- Cylinder shape is allowed to have 3 sides, and can have an odd number of sides.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1348463/
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1348434/
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1346757/

Bug Fix Collection

---

Runtime/Core/ActionResult.cs
Runtime/Core/ShapeGenerator.cs

Updating some parts of the code regarding Amy's remarks 

Fixing old comments, adding doc and fixing wrong return type

---

LICENSE.md
Third Party Notices.md

Update license and third party files for the STAR Legal review process:
https://jira.unity3d.com/browse/STAR-3473
Thank you for filling out the forms. Here are my comments:
1. Please can you confirm that the correct contributions wrapper is in place - please see section 2 of the License Assignment Guide which explains how that must be set up if Unity is accepting contributions. License Assignment Guide link is here: https://docs.google.com/document/d/19asl21ovg6SKY9k5xnukFAXCYHx7u89MQOoWEtrMZEU/edit# 
2. I've checked and verified the Third Party Notices.md file. This all looks good except the formatting/ presentation of the information is not in line with what we require for reporting purposes. Please see section 3 of the License Assignment Guide for information but to assist you I have …

Star review legal update

---

Editor/EditorCore/EditorUtility.cs

[Brief summary of the changes in this PR.]
**Fogbugz:**
**Jira:**

Removed usage of disconnected prefab instance as the state is removed

---

Third Party Notices.md

Updating third party notice
Updating third party notice
**Jira:** https://jira.unity3d.com/browse/STAR-3473

Updating third party notice

---

CHANGELOG.md
Runtime/Shapes/Stairs.cs

Fixes a missing shape generation parameter.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1407039/

fix stair properties missing inner radius setting

---

.buginfo

Internal change, add bug tracking file.

add .buginfo file

---

CHANGELOG.md
package.json
validationExceptions.json

Collections of bug fixers and version bump to 5.0.5
**Jira:**
https://jira.unity3d.com/browse/STO-2603

update changelog and package for version bump

---

CHANGELOG.md
Content/Shader/FacePicker.shader
Runtime/Core/SelectionPickerRendererStandard.cs

Backport.
**Jira:** https://jira.unity3d.com/browse/PBLD-15

Backport of fix for the PBLD-15 bug

---

Runtime/Core/ActionResult.cs
Runtime/MeshOperations/MeshValidation.cs

Reverting a breaking API change identified during PB 5.0.5 publication process

Reverting breaking API change

---

.npmignore
CHANGELOG.md
package.json

Bumping package version
**Jira:** https://jira.unity3d.com/browse/STO-2603

bumping package version to 5.0.6

---

CHANGELOG.md
Editor/EditorCore/BezierSplineEditor.cs
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/EntityVisibility.cs
Editor/EditorCore/LightmapUVEditor.cs
Editor/EditorCore/Lightmapping.cs
Editor/EditorCore/RepairActions.cs
Editor/EditorCore/UndoUtility.cs
Editor/MenuActions/Object/GenerateUV2.cs
Editor/MenuActions/Selection/SelectMaterial.cs
Editor/MenuActions/Selection/SelectVertexColor.cs
Runtime/Core/InternalUtility.cs

minor fix updates use of obsolete api for 2023.1.

update obsolete api for 23.1

---

CHANGELOG.md
package.json

```
- [case: PBLD-48] Fixed a bug where the minimum size of a shape did not take into account snap and grid sizes.
- [case: PBLD-34] Fixed a bug where `Experimental Features Enabled` was not activating when using `Dedicated Server` platform.
- [case: PBLD-41] Fixed an issue where UV distribution metric would not recalculate after the mesh optimization step.
- [case: PBLD-32] Fixed `New Shape` start location being incorrect after using right mouse button.
- [case: PBLD-19] Fixed shape creation when the camera perspective is set to Top.
- Made minor performance improvements and reduced allocations when querying for components.
- [case: PBLD-38] Fixed an issue where exported assets would incorrectly use the UInt32 mesh index format.
- [case: PBLD-43] Fixed an issue where activating the …
```

update changelog and package version to 5.0.7

---

.yamato/promotion.yml
.yamato/upm-ci.yml

Remove deprecated images and update VM images according to guidelines:
https://internaldocs.unity.com/package_development/package-ci/

Yamato image update

---

CHANGELOG.md
Editor/EditorCore/CutTool.cs.meta
Editor/EditorCore/EditorToolsContexts.cs.meta

Fixes a warning on import caused by merge conflicts in two meta files.
**Jira:** UUM-43960

fix merge conflicts in meta files

---

CHANGELOG.md
LICENSE.md
package.json

Updating package version to 5.1.1
**Jira:** https://jira.unity3d.com/browse/STO-2995

Updating package version to 5.1.1

---

Runtime/MeshOperations/CombineMeshes.cs

Clarify use of argument in CombineMeshes function docs.
**Jira:** PBLD-85

CombineMeshes Doc Fix

---

CHANGELOG.md

Package bump to 5.2.0.
(package.json file is already up to date :) )
**Jira:** https://jira.unity3d.com/browse/STO-3080

Package bump to 5.2.0

---

.buginfo

Fix typo in the .buginfo https://unity.slack.com/archives/C053SPN16UF/p1696345717830779

Fix buginfo typo

---

CHANGELOG.md
package.json

bumping package version to publish new fix
**Jira:**

Package bump to 5.2.2

---

CHANGELOG.md
package.json

rc-6.0.1-pre.1

---

CHANGELOG.md
LICENSE.md
package.json

Publish new ProBuilder preview version
**Jira:** 

Probuilder 6.0.2-pre.2

---

CHANGELOG.md
package.json

Bumping package version for release.

Probuilder 6.0.1

---

Documentation~/TableOfContents.md
Documentation~/whats-new.md

Update What's New in ProBuilder page to summarize new features in ProBuilder 6. Also, fix changelog link. 
**Jira:** DOCATT-5647

Update ProBuilder 6 What's New Page

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditorShortcuts.cs
Editor/MenuActions/Interaction/ToggleSelectBackFaces.cs

fixing shortcuts description, and tooltip.
Also fixing the shortcut to toggle PB Context to make it work.
**Jira:** https://jira.unity3d.com/browse/PBLD-121

[PBLD-121] Fixing tooltips and shortcut

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditor.cs
Editor/EditorCore/ProBuilderToolsContexts.cs
Editor/Overlays/SceneInformationOverlay.cs
Editor/Overlays/SceneInformationOverlay.cs.meta
Runtime/Core/SelectionPickerRendererStandard.cs

Updating the old Scene info using a guicontent in the scene view by a regular overlay.
Before :
After:
**Jira:** https://jira.unity3d.com/browse/PBLD-120

[PBLD-120] ProBuilder Scene Info overlay

---

Documentation~/customizing.md

Updating the Customizing ProBuilder page
DOCATT-5847
Docs only

Updating customizing page

---

Documentation~/workflow-vertexcolors.md

Applying Jon's changes to the Vertex workflow page
**Jira:** DOCATT-5837
Docs only.

Docs update: Settings vertex colors page

---

Documentation~/workflow-create.md

Updating the Create meshes landing page. It had a lot of information that already exists in its child pages, so I took that info out.
DOCATT-5832
Docs only

Updating Create meshes landing page

---

Documentation~/workflow-create-polyshape.md

Update to the poly shape tool page
**Jira:** DOCATT-5834
@JonMUnity I left a comment right at the end about a note I don't understand.

Docs: Jon's updates to the poly shape tool page

---

Editor/Overlays/SceneInformationOverlay.cs

`SceneInformationOverlay` does not need to be public.
**Jira:**

Removed SceneInformationOverlay's public access modifier 

---

CHANGELOG.md

Changelog update.
**Jira:**  https://jira.unity3d.com/browse/STO-3374

[PB5] Changelog update

---

CHANGELOG.md
package.json

[Brief summary of the changes in this PR.]
**Jira:** https://jira.unity3d.com/browse/STO-3374

[PB6] Bump package version.

---

CHANGELOG.md
Editor/EditorCore/EditorToolbarMenuItems.cs

Removed conflicting menu item shortcut.
**Jira:** https://jira.unity3d.com/browse/PBLD-161

Removed conflicting menu item shortcut

---

Documentation~/hotkeys.md
Documentation~/modes.md

Adding info about the context menu + refreshing the keyboard stuff
**Jira:** DOCATT-5815
What an unusually small and focused PR! You're welcome.

Updating keyboard/context menu content

---

CHANGELOG.md
package.json

Bump package version to 6.0.4
**Jira:** https://jira.unity3d.com/browse/STO-3411

[PB6] Bump package version to 6.0.4

---

CHANGELOG.md

Minor edits to the ProBuilder changelog.

[DOCS] 6.0.5 Changelog edits

---

CHANGELOG.md
package.json

Bump version and update changelog.
**Jira:**

[6.0.5] Bump version and update changelog

---

CHANGELOG.md
package.json

Bump version and update changelog on `release/6.0`
**Jira:**

Bump version and update changelog on release branch

---

.gitignore
.npmignore
Editor/EditorCore/MenuAction.cs
Editor/EditorCore/PolyShapeTool.cs
Editor/EditorCore/ProBuilderEditor.cs
LICENSE.md

PR fixes [PVP issues](https://pkgprom.ds.unity3d.com/pvp/#results/.H_gIAJwFdovzxTLjLR8yZCxWP0S81SJ7W6kX10zZDFFmQOCokO2p7UFG3j7onNfvv2QdoNggLF19_H_vLcAATWKfB7xemhOgIZ-X96b1rY1a1eRv67a6gKVqAR8BXZPyuvOrcLLCFBoutyiqvtrto4D8KHLfdgSGonmGaiOKi_iLxV_Wx3UhiOMLAgUNo6868URUVgAdAQ0DF55eJfGF1QZURdeKRqhYz4CKtQZUom9Fo4J4QhrFX-o2qDDBNGYEXnyw9_HToJgILOjzeVrtC_NEYOxrBKPaxAxTtvokepPxOIxiBoue7FiRKRXbUyvB7Pph6aD4_WCIBbIgFiH2ku0OHV1emcjj6GkTGVKX233lsNGIFDq8zTa2in1rZmsjVj9FL3AH-7L3_4hp7TAwWIP3g2iebjxNTqJ0Fr-JlzVrXRuPXR6fWNBGPqcsSwc3VKgyGrBdAhw2S7scWNHvNy8awdH8h6CYhOs8-b9AQ6FGJtb1oilPWvWWDmh60pGX14Hrao543yedTha-dtKx3-VIAdNbpgTJ7D6CDgLNrnTd-yIat96gC1uqUOOcLvMV5edJpVbEifLC3eYQ0-3wn3WM0NbrvsCTJrBgkg-W1u7vA1ElC1XDWHlvZVklPwWTTmfuPezSRW8xT4zAr_-gS30SRB18mPqdFqlyJw9vId6giZkSzbq_224qIjtL4bPXAddmFrT41NPOTyOTO1Bem8pUCLdYR …

More PVP fixes

---

.yamato/wrench/wrench_config.json

[5.2] Wrench jobs update

---

.yamato/upm-ci.yml

Add trigger to run Yamato jobs nightly/daily against trunk
**Jira:**
Same dependencies as Test Trigger

Add Nightly Trigger

---

CHANGELOG.md
Editor/EditorCore/EditorMaterialUtility.cs
Editor/EditorCore/ObjExporter.cs
Tests/Editor/Export/ExportObj.cs

Update Access to the property type to non-obsolete call.
jira: https://jira.unity3d.com/browse/PBLD-228

correct shader property type access to use non-obsolete property
