com.unity.probuilder/Editor/EditorCore/EditorMaterialUtility.cs
com.unity.probuilder/Editor/EditorCore/EditorMaterialUtility.cs.meta
com.unity.probuilder/Editor/EditorCore/MaterialEditor.cs
com.unity.probuilder/Editor/EditorCore/MeshSelection.cs
com.unity.probuilder/Editor/EditorCore/Model.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs
com.unity.probuilder/Editor/EditorCore/SceneDragAndDropListener.cs
com.unity.probuilder/Editor/EditorCore/UVEditor.cs
com.unity.probuilder/Runtime/Core/MaterialUtility.cs
com.unity.probuilder/Runtime/Core/MaterialUtility.cs.meta
com.unity.probuilder/Runtime/Core/MeshUtility.cs
com.unity.probuilder/Runtime/Core/ProBuilderMeshFunction.cs

- Fix an error where the Material Editor window would turn completely black when an SRP material is assigned to the "Quick Material" field
- Fix "Match Selection" button not taking the active face selection (previously it took the first selected face, now it matches the active selection, or last selected 👈  @gabrielw-us )
https://fogbugz.unity3d.com/f/cases/1125118/

Fix Material Editor incompatibilities with SRP materials

---

com.unity.probuilder/Runtime/Core/Math.cs

PointInPolygon previously used Vector2.up for the point used to check if the target point intersects with any of the edges. It meant that if the target point, one point on the polygon and the center of the bounds formed by the polygon had the same Y, the function would say that the point isn't in the polygon.
This situation has a low chance to happen, but this fix lessens it even more where it's highly improbable to happen.

Lessen edge case where PointInPolygon would return the wrong value

---

com.unity.probuilder/Editor/EditorCore/ShapeEditor.cs

Using the shape tool to build an object should now dirty the scene and the action should be undoable.

Fixed Shape Tool create not being added to the undo stack

---

com.unity.probuilder/Editor/EditorCore/MaterialEditor.cs

Fix this case: https://unity3d.atlassian.net/browse/WB-1193

Fix MaterialEditor not filtering out unused submesh index when applying new material.

---

com.unity.probuilder/Editor/EditorCore/UVEditor.cs

In the UV Editor, user can only scroll the UV view (grid) and not the actions window that is embedded. This PR fixes that issue by checking when we scroll if mouse is hovering the actions window. If so, we don't scroll the UV view and don't consume the event.
Fix this case: https://unity3d.atlassian.net/browse/WB-1260

Fix Action window in UVEditor not scrollable.

---

com.unity.probuilder/Editor/EditorCore/EditorSceneViewPicker.cs

(WIP - REQUESTING QA FIRST)
Goal of this PR:
When picking Faces, sometimes deep selection is triggered when we try to pick a face that has been already selected through Ctrl + Click action. This PR fixes this by storing the append selection state. We reset the DeepSelectionPrevious when we switch from/to append selection.
Fix this case: https://unity3d.atlassian.net/browse/WB-424

Deep selection on faces shouldn't trigger when multiple faces are selected

---

com.unity.probuilder/Editor/EditorCore/PositionMoveTool.cs
com.unity.probuilder/Editor/EditorCore/PositionRotateTool.cs
com.unity.probuilder/Editor/EditorCore/PositionScaleTool.cs
com.unity.probuilder/Editor/EditorCore/PositionTool.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs

Prior to 4.0.0 there was a display for scene view tool deltas. It got lost in the tools refactor, and this PR adds it back in as a part of the `PositionTool`.

Add missing tool info in SceneView

---

com.unity.probuilder/Runtime/Core/Projection.cs
com.unity.probuilder/Runtime/MeshOperations/UV/UVEditing.cs

WB-1262
Fixes an issue where Planar and Box projection for Manual UVs would not calculate the projection direction correctly, resulting in skewed UVs.

Fix Manual UV projection

---

com.unity.probuilder/Editor/EditorCore/AutoUVEditor.cs
com.unity.probuilder/Runtime/Core/Math.cs
com.unity.probuilder/Runtime/Core/ProBuilderMeshFunction.cs
com.unity.probuilder/Runtime/MeshOperations/UV/UvUnwrapping.cs

[WB-1085]
**Issues Fixed:**
- Change to one member of a UV group would not replicate on all other member of the group
- The UV settings would be applied to every faces individually instead of being applied to all faces at once. For example, the face would all be rotated around their own pivot instead of being rotated around the pivot of the entire group.

Fix UV groups

---

com.unity.probuilder/Editor/EditorCore/EditorSceneViewPicker.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs

[Jira: WB-996]
**Problem:** 
With the currently high picking distance being the only option, selecting another object near your current selection can be annoying (See image bellow).
**Solution:**
A modifier is now applied to the distance of a vertex/edge if the user is currently hovering another probuilder mesh. This prioritizes the hovered mesh over the selected mesh.
I also added a slider for picking distance in preferences to make it available in developer mode. (Default value stays what the constant value used to be).

Added dynamic picking distance based on current object hovered

---

com.unity.probuilder/Editor/EditorCore/UVEditor.cs

[Jira: WB-1307]
If the user didn't have a selection, it would require the user to click on a face twice before getting the right _Actions_ window.

Fixed if nothing selected, then select UV face, wrong info is shown

---

com.unity.probuilder/Editor/EditorCore/EditorSceneViewPicker.cs

[Jira: WB-1023]
When drag selecting, the _n_ shared vertices would get picked up instead of just one like with CTLR+left click (which is the correct behaviour). CTRL/Shift+left click now removes every vertex sharing the same shared vertex you clicked.

Fixed deselecting vertices sometimes not working properly

---

com.unity.probuilder/Editor/EditorCore/EditorSceneViewPicker.cs

[Jira: WB-1217]
**Problem:**
If the vertex is the closest point to the mouse, one of the 3 edges that connect that vertex will be hovered, even if it's behind the mesh.
**Solution:**
Check the distance to the camera when multiple edge have the closest distance to the mouse to determine which one is closer.

Fixed edge hover goes through selected mesh

---

com.unity.probuilder.tests/Tests/Runtime/MeshOps/UV/ConvertManualToAutoUVTests.cs
com.unity.probuilder.tests/Tests/Runtime/MeshOps/UV/ConvertManualToAutoUVTests.cs.meta
com.unity.probuilder/Content/Resources/Materials/FacePicker.mat
com.unity.probuilder/Debug/Editor/TempMenuItems.cs
com.unity.probuilder/Editor/EditorCore/TextureMoveTool.cs
com.unity.probuilder/Editor/EditorCore/TextureTool.cs
com.unity.probuilder/Editor/EditorCore/UVEditor.cs
com.unity.probuilder/Runtime/Core/Bounds2D.cs
com.unity.probuilder/Runtime/Core/ProBuilderMeshFunction.cs
com.unity.probuilder/Runtime/Core/Projection.cs
com.unity.probuilder/Runtime/MeshOperations/UV/AutoUvConversion.cs
com.unity.probuilder/Runtime/MeshOperations/UV/UvUnwrapping.cs

Fixes an issue where translating a face's texture selection would not account for the object scale or it's projected UV scale.
https://unity3d.atlassian.net/browse/WB-120
This fix only works for faces, for which in most cases a sane scale value value can be parsed. Translating vertices and edges will still have the appearance of moving out of sync with the translation handle.

Fix texture tool translation appearing to affect scaled UVs disproportionately

---

com.unity.probuilder/Content/Shader/PointBillboard.shader
com.unity.probuilder/Content/Shader/VertexPicker.shader
com.unity.probuilder/Editor/EditorCore/EditorMeshHandles.cs
com.unity.probuilder/Editor/EditorCore/StaticEditorMeshHandles.cs
com.unity.probuilder/Runtime/Core/MeshHandles.cs

https://unity3d.atlassian.net/browse/WB-695
It is most noticeable in iso views.
This also reduces the amount of offset applied to vertex billboards when in iso mode and using geometry shaders from .98 to .99.

Fix vertex preview highlight rendering slightly offset of vertex

---

com.unity.probuilder/Debug/Editor/GenerateMenuItems.cs
com.unity.probuilder/Editor/EditorCore/EditorToolbarMenuItems.cs
com.unity.probuilder/Editor/MenuActions/Object/SetTrigger.cs

Fixes an issue where ShortcutManager would report conflicting shortcuts for MenuItems sharing a KeyCombination but differentiated by context.

remove menuitem shortcut conflicts

---

com.unity.probuilder/Content/Resources/Materials/FacePicker.mat
com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderSettings.cs

Previously it was a requirement to call `ProBuillderSettings.Save` at some point after modifying a project setting. Now settings are automatically saved when the application exits.
https://unity3d.atlassian.net/browse/WB-1358

Save all settings on application quit

---

com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderEditorShortcuts.cs

- `Escape` now sets `SelectMode.Object`
- `Edit {Edges, Faces, Vertices}` now enters the select mode

Fix SelectMode shortcuts not working

---

com.unity.probuilder/Debug/Editor/SelectionDebug.cs
com.unity.probuilder/Debug/Editor/SelectionDebug.cs.meta
com.unity.probuilder/Editor/EditorCore/DimensionsEditor.cs
com.unity.probuilder/Editor/EditorCore/MaterialEditor.cs
com.unity.probuilder/Editor/EditorCore/MeshAndElementSelection.cs
com.unity.probuilder/Editor/EditorCore/MeshSelection.cs
com.unity.probuilder/Editor/EditorCore/PositionMoveTool.cs
com.unity.probuilder/Editor/EditorCore/PositionRotateTool.cs
com.unity.probuilder/Editor/EditorCore/PositionTool.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs
com.unity.probuilder/Editor/EditorCore/ProBuilderMeshEditor.cs
com.unity.probuilder/Editor/EditorCore/UVRenderOptions.cs
com.unity.probuilder/Editor/EditorCore/VertexManipulationTool.cs
com.unity.probuilder/Editor/MenuActions/Selection/SelectFaceRing.cs
com.unity.probuilder/Runtime/Core/Edge.cs
com.unity.probuilder/Runtime/Core/Face.cs

Fixes the following issues related to `ProBuilderMesh` retaining distinct element selection caches.

Fix inconsistencies in handle and actions when `SelectMode` is changed

---

com.unity.probuilder.tests/Tests/Runtime/Type/TestVector.cs
com.unity.probuilder/Debug/Editor/GenerateMenuItems.cs
com.unity.probuilder/Debug/Editor/TempMenuItems.cs
com.unity.probuilder/Editor/EditorCore/ObjExporter.cs
com.unity.probuilder/Editor/MenuActions/Export/ExportObj.cs
com.unity.probuilder/Runtime/Core/IntVec2.cs
com.unity.probuilder/Runtime/Core/IntVec2.cs.meta
com.unity.probuilder/Runtime/Core/IntVec3.cs
com.unity.probuilder/Runtime/Core/IntVec4.cs
com.unity.probuilder/Runtime/Core/IntVec4.cs.meta
com.unity.probuilder/Runtime/Core/Submesh.cs
com.unity.probuilder/Runtime/Core/VectorHash.cs

This change enables the obj exporter to share vertex positions, normals, and textures. It reduces file sizes, as well as translates coincident vertices to other DCCs.
This also fixes an issue when attempting to copy a built-in texture resource.

Fix obj exporting separate faces

---

com.unity.probuilder/Runtime/Core/Submesh.cs
com.unity.probuilder/Runtime/MeshOperations/MeshImporter.cs

Fix `MeshImporter.Import` resulting in all faces having a `submeshIndex` value of `0`. The problem was that `Import` adds the `ProBuilderMesh` component with `AddComponent` and does not initialize the `m_MeshFormatVersion` correctly. This PR introduces a null check in `Submesh.MapFaceMaterialsToSubmeshIndex` to prevent it from overwriting the submesh index in faces with null materials.

ProBuilderize replaces all materials on object with default PB material

---

com.unity.probuilder/Editor/EditorCore/EditorMeshUtility.cs
com.unity.probuilder/Editor/EditorCore/MeshSelection.cs
com.unity.probuilder/Editor/EditorCore/RepairActions.cs
com.unity.probuilder/Editor/MenuActions/Geometry/WeldVertices.cs
com.unity.probuilder/Runtime/Core/ArrayUtility.cs
com.unity.probuilder/Runtime/Core/ProBuilderMeshFunction.cs
com.unity.probuilder/Runtime/Core/ProBuilderMeshSelection.cs
com.unity.probuilder/Runtime/Core/SharedVertex.cs
com.unity.probuilder/Runtime/MeshOperations/ConnectElements.cs
com.unity.probuilder/Runtime/MeshOperations/DeleteElements.cs
com.unity.probuilder/Runtime/MeshOperations/MergeElements.cs
com.unity.probuilder/Runtime/MeshOperations/MeshValidation.cs
com.unity.probuilder/Runtime/MeshOperations/MeshValidation.cs.meta
com.unity.probuilder/Runtime/MeshOperations/Triangulation.cs
com.unity.probuilder/Runtime/MeshOperations/VertexEditing.cs

Fixes fogbugz case 1077016
This also cleans up the functions to remove degenerate triangles and unused vertices, moving them to a new `MeshValidation` class. A new method is added (`MeshValidation.EnsureMeshIsValid`) which cleans up degenerate tris and unused vertices while keeping the selection intact.

Fix Connect Edges throwing exception with degenerate tris

---

com.unity.probuilder/Editor/EditorCore/ProBuilderEditor.cs
com.unity.probuilder/Editor/MenuActions/Interaction/ToggleDragRectMode.cs
com.unity.probuilder/Editor/MenuActions/Interaction/ToggleDragSelectionMode.cs
com.unity.probuilder/Editor/MenuActions/Interaction/ToggleSelectBackFaces.cs

Fixes fb ticket 1093594
- Makes some properties on ProBuilderEditor static that should have been static in the first place (pref values)

Fix a null ref when maximizing then minizing the toolbar window

---

com.unity.probuilder/Editor/MenuActions/Export/Export.cs
com.unity.probuilder/Editor/MenuActions/Export/ExportAsset.cs

- splits the `Export Asset` option into two exporters, one for just the `Mesh` and one for `Mesh & Prefab` (latter is current behavior)
- adds an option to replace the original objects with the exported objects

Add option to Export just mesh asset

---

com.unity.probuilder/Runtime/Core/Shortcut.cs

https://forum.unity.com/threads/probuilder-probuilderpreferences-asset-not-saving.533772/#post-4374817
Fixes an issue with the `Shortcut` class not being saved to project settings.

Fix shortcut class not serializing

---

com.unity.probuilder/Content/Shader/FaceHighlight.shader
com.unity.probuilder/Content/Shader/FacePicker.shader
com.unity.probuilder/Content/Shader/NormalPreview.shader
com.unity.probuilder/Content/Shader/ReferenceUnlit.shader
com.unity.probuilder/Content/Shader/SmoothingPreview.shader
com.unity.probuilder/Content/Shader/TransparentOverlay.shader
com.unity.probuilder/Content/Shader/UnlitSolidColor.shader
com.unity.probuilder/Content/Shader/UnlitVertexColor.shader
com.unity.probuilder/Content/Shader/VertexPicker.shader

Fixes fogbugz ticket 1083088
This fixes some incorrect tags and blend modes in shaders. In most cases the errors are benign, but in some instances result in flickering and incorrectly discarded pixels.

Fix Unlit Solid Color shader flickering in Forward Rendering path

---

com.unity.probuilder/Editor/Unity.ProBuilder.Editor.asmdef
com.unity.probuilder/Runtime/Unity.ProBuilder.asmdef

Removes the requirement that projects wanting to use the ProBuilder API also make use of Assembly Definition files.

Make assemblies auto referenced by default

---

Editor/EditorCore/ProBuilderEditor.cs

The selection info box was not updating the `selected elements` correctly, this fixes it.

fix selection info lagging one selection behind

---

Editor/EditorCore/EditorHandleUtility.cs

Modified FindBestPlane to handle picking Terrain.
Note: Tried to create a unit test without success because FindBestPlane relies on UnityEditor.HandleUtility.PickGameObject which cannot be called outside OnGui calls.

Allow picking on a Terrain when trying to get the best plane.

---

Editor/EditorCore/ObjExporter.cs
Editor/MenuActions/Export/ExportObj.cs
Tests/.tests.json
Tests/Editor/Export/ExportObj.cs
Tests/Editor/Export/ExportStl.cs
Tests/Framework/TestUtility.cs
Tests/Runtime/MeshOps/ProBuilderizeTests.cs

WB-1492
Fixes an issue where the obj exporter would incorrectly offset additional mesh groups by the original vertex count instead of the coincident merged counts.
Adds new unit tests for obj export.

Fix obj export with multiple meshes creating invalid files

---

Editor/EditorCore/MeshSelection.cs
Editor/MenuActions/Geometry/SplitVertices.cs
Runtime/Core/ProBuilderMeshSelection.cs

Fixes WB-1359
Split Vertex action now operates on all coincident vertices in the selection, not just the selected indices.

Collect coincident vertices when doing split vertices action

---

Addons/Fbx.cs

use reflection to check if the FBX exporter assembly is present and hook up the delegate.

Ut 2109 fix FBX exporter link

---

Editor/EditorCore/MenuActionStyles.cs

On macOS font size from USS does not always get passed on to custom styles. This PR sets the font size on the custom styles used by the ProBuilder toolbar.

FIx toolbar font size on macOS with Unity 2019.3

---

Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/PolyShapeEditor.cs
Editor/EditorCore/PositionMoveTool.cs
Editor/EditorCore/ProBuilderEditor.cs
Editor/EditorCore/ProGridsInterface.cs
Editor/EditorCore/TextureMoveTool.cs
Editor/EditorCore/TextureRotateTool.cs
Editor/EditorCore/UVEditor.cs
Runtime/Core/ProGridsSnapping.cs
Runtime/Core/ProGridsSnapping.cs.meta
Runtime/Core/VertexPositioning.cs

Unity 2019.3 introduces a new `Snapping` class in the `UnityEngine` namespace. This make `UnityEngine.ProBuilder.Snapping` ambiguous.

Rename Snapping class to avoid conflicts with UnityEngine.Snapping

---

Editor/EditorCore/BooleanEditor.cs

When the donor objects are modified from the ObjectField instead of drag and drop into the preview wells.
Fixes Fogbugz case 1062439

Fix boolean preview not updating if shapes

---

.yamato/upm-ci.yml
Editor/EditorCore/ProBuilderEditor.cs

Issue: https://issuetracker.unity3d.com/issues/probuilder-editor-throws-a-nullreferenceexception-when-scene-view-is-focused-and-button-g-is-pressed

Fixed null reference when pressing G without the probuilder toolbar

---

Editor/EditorCore/MenuAction.cs

With a recent change in trunk, it's now not needed to have a texture in a style to use GUI.backgroundColor. I've reordered the GUI.backgroundColor call so it doesn't affect our GUI.BeginHorizontal rect.
What it looked like:

Fixed issue with background color applying to entire probuilder menu action

---

Editor/MenuActions/Geometry/WeldVertices.cs

https://fogbugz.unity3d.com/f/cases/1168432/
The problem was that after cleaning up degenerate triangles, the Weld action would try to preserve the selected vertices. When there are no vertices left in the mesh, the results would be a mesh selection of `-1` values, which the shared vertex lookup doesn't expect.

Fix null-ref when Weld results in invalid mesh topology

---

Editor/MenuActions/Object/MergeObjects.cs
Runtime/Core/TransformUtility.cs
Runtime/MeshOperations/CombineMeshes.cs
Tests/Runtime/MeshOps/CombineMeshesTests.cs
Tests/Runtime/MeshOps/CombineMeshesTests.cs.meta

Basically in the past all objects were merged to new ProBuilderMesh. Right now we re-use the active mesh as the first target to re-use.
This address WB-1372 and WB-1373 as well.

Wb 1396 merge objects retain properties

---

Editor/EditorCore/Lightmapping.cs
Editor/EditorCore/PreferencesUpdater.cs
Tests/Weekly/LightmapUVsAreValid.cs

https://ono.unity3d.com/unity/unity/pull-request/95782/_/lighting/lighting-settings-asset-take2 will hopefully land in 20.1 and will make all old settings API points for Lightmapping obsolete. They are still usable but will fire a warning. These changes make sure that we can still use the old API but it won't cause compile or runtime issues.
Testing status
Manual Tests: What did you do?
Nothing. It all seems to work with just disabling this warning. Have had to do this on a lot of code before.
Comments to reviewers
There is an internal API called Lightmapping.GetLightingSettingsOrDefaultsFallback() but we can't allow this to be public since we can't allow users to possibly change the global default settings that is read-only. Not sure how to do this in a nicer way for HDRPs right now.

Disable warning for deprecation of Lightmapping API

---

Editor/EditorCore/Pref.cs
Editor/EditorCore/ShapeEditor.cs
QAReport.md

Fogbugz ticket: https://fogbugz.unity3d.com/f/cases/1192935/
- Fixes errors thrown when entering play mode with the Shape Tool open
- Makes shape settings persistent as user settings
- No longer creates and destroys the current selection, causing a re-select of the active transform

Fix Shape Tool errors on entering Play Mode (plus minor improvements)

---

Editor/EditorCore/PolyShapeEditor.cs

fogbugz https://fogbugz.unity3d.com/f/cases/1193983/
Previously creating a new `Polyshape` object would delete the object if the Inspector lost focus before the user completes the shape. Now the shape is just committed as is (allowing empty points). Fixes the same issue when pressing `Escape` during initial shape editing.

Fix Polyshape Editor deleting GameObject if losing focus with no input

---

CHANGELOG.md
Runtime/Core/BuiltinMaterials.cs
Runtime/Core/ProBuilderMeshSelection.cs
package.json

https://forum.unity.com/threads/errors-and-cant-select-verticies.791490/
Fixes an issue where the `ProBuilderMesh` selection cache could end up in an unrecoverable state, preventing the mesh from being editable.

Fix SelectionCache throwing errors

---

Editor/EditorCore/EditorGUILayout.cs
Editor/EditorCore/EditorGUIUtility.cs

[[case #1183100]](https://fogbugz.unity3d.com/f/cases/1183100/)
Our Free Slider would look like this when the target platform was android:
It also look a bit weird on windows (you can see the difference by looking at the curvature field which is a normal unity slider):
Result with the fix on both platform:

Fixed Issue With Free Slider Height When On Android Platform Target

---

CHANGELOG.md
Editor/EditorCore/ShapeEditor.cs

https://fogbugz.unity3d.com/f/cases/1204742/
Fixes an issue where assigning null to the New Shape editor preview object would throw errors.

4.1: Fix errors when assigning null mesh to preview shape

---

Runtime/Core/TransformUtility.cs
Tests/Runtime/Utilities.meta
Tests/Runtime/Utilities/TransformUtilityTests.cs
Tests/Runtime/Utilities/TransformUtilityTests.cs.meta

[[case#1208475]](https://fogbugz.unity3d.com/f/cases/1208475/)
@JoelFortin The unparent/reparent utility method that was changed is only use in the _Center Pivot_ Action and _Set Pivot To Selection_ Action and nowhere else in the code.

Fixed Issue When Changing Pivot If the Transform Has Children

---

Editor/EditorCore/EditorMeshHandles.cs
Editor/EditorCore/EditorSceneViewPicker.cs
Editor/EditorCore/ProBuilderEditor.cs
Editor/EditorCore/StaticEditorMeshHandles.cs

https://fogbugz.unity3d.com/f/cases/1173650 and https://issuetracker.unity3d.com/issues/probuilder-unable-to-select-face-slash-vertex-of-the-game-object-when-using-pb-toolbar
Fixes an issue where the scene picker preferences would in some cases (still unknown how these cases occur) could fail to initialize, resulting in the maximum allowed picking distance to be set to 0, effectively blocking any element from being selected. This PR sets the max pick distance to a constant value, which currently is a hidden setting.
Also fixes an issue where the hover preview would incorrectly highlight elements that are outside the picking range.

Fix Element Selection Sporadic Failures

---

Editor/EditorCore/MeshSelection.cs
Runtime/Core/ProBuilderMesh.cs
Runtime/Core/ProBuilderMeshFunction.cs

Today, when an user manually reset a ProBuilderMesh component, he looses the internal mesh data but the SceneView doesn't refresh what it renders.
This PR ensures two things:
- We rebuild a mesh based on the new set of data after a Reset(). In this case, it would result into an empty mesh.
- ProBuilderEditor will refresh its selection to behave in respect with the new data.
Fix this case: https://fogbugz.unity3d.com/f/cases/1196134

Ensure to update internal data when users manually reset components.

---

Editor/EditorCore/ObjExporter.cs

fix for https://fogbugz.unity3d.com/f/cases/1205318/
Legacy uses _Color keyword
HDRP uses _BaseColor and _Color
URP uses _BaseColor
rather dependant on how shaders are written

added case for URP/HDRP shaders

---

CHANGELOG.md
Editor/EditorCore/UnityScenePostProcessor.cs

https://fogbugz.unity3d.com/f/cases/1214103/
Fixes the `Mesh Filter` component not being included in builds.

Fix build process removing MeshFilter component

---

CHANGELOG.md
Editor/EditorCore/TooltipEditor.cs

Fixed tooltips in the ProBuilder toolbar not rendering on macOS.
https://fogbugz.unity3d.com/f/cases/1211721/

Fix tooltips not showing on macos

---

CHANGELOG.md
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/PolyShapeEditor.cs
Editor/EditorCore/ShapeEditor.cs
Editor/MenuActions/Editors/NewPolyShape.cs
package.json

https://fogbugz.unity3d.com/f/cases/1223330/

Fix PolyShape Undo Errors

---

CHANGELOG.md
Runtime/MeshOperations/Bevel.cs

Fixes an issue where the Bevel action only tested a subset of the newly created faces for normal conformity.
https://fogbugz.unity3d.com/f/cases/1132509/

Fix Bevel sometimes producing non-conformed normals

---

CHANGELOG.md
Debug/Editor/GenerateMenuItems.cs
Editor/EditorCore/EditorToolbarMenuItems.cs
Editor/EditorCore/PolyShapeEditor.cs
Editor/EditorCore/ShapeEditor.cs
Editor/EditorCore/UVEditor.cs
Runtime/Core/Math.cs
package.json

Fix collection 0

---

CHANGELOG.md
Runtime/Core/ProBuilderMesh.cs

It was just missing a null check. In the editor it is caught by the cache invalidation, but since that doesn't run at runtime it was never initializing.

Fix ProBuilderMesh.sharedTextureLookup throwing exception at runtime

---

CHANGELOG.md
Editor/EditorCore/ProBuilderSettingsProvider.cs
Editor/EditorCore/ShapeEditor.cs
Editor/MenuActions/Editors/OpenShapeEditor.cs
Runtime/Core/Math.cs

The `New Shape` menu item now creates the last selected shape with it's last set parameters instead of always building a cube primitive with the default values.

Fix "New Shape" menu action always building a cube

---

CHANGELOG.md
Editor/EditorCore/UnityScenePostProcessor.cs
Runtime/Core/ProBuilderMesh.cs
Runtime/Core/ProBuilderMeshFunction.cs
Runtime/Core/SerializationUtility.cs
Tests/Editor/Editor/ReflectedMethodsExist.cs
Tests/Editor/Object/CreateDestroy.cs
Tests/Editor/Object/PrefabTests.cs

This feature was causing a lot of unnecessary mesh rebuilds due to the MeshFilter no longer serializing a reference the generated mesh. 
Most critically, it breaks the mesh persistence when entering play mode and prefab stages. This makes it nearly impossible to work with a ProBuilder created mesh within other systems.
This feature is still in code behind a pre-processor flag. Once a fix is found for the mesh persistence issue we should re-enable this feature.

Disable Driven Properties and MeshFilter DontSave flag

---

CHANGELOG.md
Editor/EditorCore/EditorMeshHandles.cs
Editor/EditorCore/StaticEditorMeshHandles.cs
Runtime/Core/ObjectPool.cs

Fixes `EditorMeshHandles` not using the correct `HideFlags` for internal resources, which resulted in them being destroyed at incorrect times.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1230949/

Fix EditorMeshHandles using incorrect HideFlags for resources

---

CHANGELOG.md
Editor/EditorCore/StripProBuilderScripts.cs
Tests/Editor/Actions/StripProBuilderScriptsTest.cs

Fixed null exception when trying to strip scrip from a Bezier Shape.
https://fogbugz.unity3d.com/f/cases/1245491/

Removing bezier shape + Tests

---

CHANGELOG.md
Editor/EditorCore/EditorHandleUtility.cs
Editor/EditorCore/ProBuilderEditor.cs

Fixes an issue where the 2D move and scale tools would throw exceptions when accessed from the UV Editor. This is regressed behaviour from Unity 2020.1, but we were using the Handles incorrectly in the first place so as a quick fix we can just restrict calls into the Handles cap functions to repaints.
Someday, someone should rewrite the 2D handles to use the normal handles instead of rolling our own solution.

quick fix for null ref in uv editor window

---

CHANGELOG.md
Editor/EditorCore/EditorToolbar.cs
Editor/MenuActions/Object/ProBuilderize.cs

Currently, if you have an active selection in Hierarchy that hasn't been ProBuilder-ized yet and open the main window, the action is not enabled.
This PR enables the action immediately, instead of having to deselect the object and select it again so the action is finally enabled in the action palette.
That's my first contribution, I hope I didn't forget anything and it's properly done, let me know otherwise !

Ensure "ProBuilderize" is available at window init

---

CHANGELOG.md
Editor/EditorCore/TooltipEditor.cs

Fixes an issue where calling `Tooltip.Hide` would negatively affect editor performance.

fix TooltipEditor.Hide calling FindObjectsOfTypeAll

---

CHANGELOG.md
Editor/EditorCore/ShortcutManager.cs

Preferences are normally change when the value is set but in the case of shortcut we modify the array directly. This PR ensure that changing the shortcut from the UI saves the changes.
**Fogbugz:** [case#1259506](https://fogbugz.unity3d.com/f/cases/1259506/)

Fixed Shortcuts Not Being Saved in 2018.4

---

CHANGELOG.md
Content/Shader/ScrollHighlight.shader

UNITY_PASS_FORWARDBASE macro instruction was causing a warning message when using probuilder in URP from the shader :
Hidden/ProBuilder/ScrollHighlight
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1281254/
Not sure that all Probuilder Shaders have been fully verified for SRP?

Fixed shader warning in URP for UNITY_PASS_FORWARDBASE redefinition

---

CHANGELOG.md
Runtime/Core/ProBuilderMeshFunction.cs

As selection is serialized, it is saved with the scene.
When loading a scene, the previous selection is loaded with the ProBuilderMesh even if not selected.
This results in weird behaviors when trying to apply material on PB objects right after loading the scene.
The PR just ensures selection is cleared on ProBuilder's meshes.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1286045/
**Jira:**

Ensuring that selection is clear at start

---

CHANGELOG.md
Editor/EditorCore/TooltipEditor.cs

Fix tooltip display that was going out of screen when screen was using a zoom (different dpi).
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1285651/
**Jira:**

Adding dpi screen resolution to handle tooltip placement

---

CHANGELOG.md
Editor/EditorCore/PolyShapeEditor.cs

The poly shape point insertion was fixed while switching to an Editor Tool for version 5. This PR backports this fix to version 4.
**Bug Report on Forum:** https://forum.unity.com/threads/creating-a-new-point-on-poly-shape-is-really-difficult-interface.1006952/
The fix is mostly from this [commit](https://github.com/Unity-Technologies/com.unity.probuilder/commit/ec6d85bbc7a6608c27b137794242f52cbb03bcf7) and was manually merged back into PolyShapeEditor.

[Backport] Poly Shape Point Insertion Fix

---

CHANGELOG.md
Editor/EditorCore/EditorUtility.cs

Having the ProBuilder package 4.4 installed causes Unity 2018.4 to output "Warning: Annotation not found!" every time a script is recompiled.
Seems that getting the annotation array before setting the icon remove the warning.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1294866/

V4.4/bugfix 1294866 annotation warning

---

CHANGELOG.md
Runtime/Core/MeshUtility.cs
Runtime/Unity.ProBuilder.asmdef
package.json

Removing the module Particle System or IMGUI was causing compilation errors. Added both of those as dependencies. I validated that removing everything in the manifest file didn't cause any other errors.

Added Missing Dependency Builtin Modules

---

CHANGELOG.md
Editor/EditorCore/CutTool.cs
Runtime/MeshOperations/AppendElements.cs

Fixing problem occurring when subdividing an edge on a PB Mesh with multiple materials assigned to the faces.
The fix ensure the submesh index is kept when duplicating the face.
Before the fix:
After the fix:
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1311258/

Fix for material reverting when subdividing an edge

---

CHANGELOG.md
Content/Shader/EdgePicker.shader
Content/Shader/FaceHighlight.shader
Content/Shader/LineBillboardMetal.shader
Content/Shader/ProBuilderCG.cginc

Fixing edge selection using rect box selection that was broken with some Unity version.
The fix is using the same principle that the highlight shader is using : the edge picker shader is bringing edges a little closer to the camera plane to avoid z-fighting problem. This z-fighting was causing the problematic rendering in the texture.
However the problem was really inconsistent and reproduction was not always possible.
It seems the problem was coming from a problem with depth precision and was present on some Unity 20.2 versions.
Here is an example of the broken selection :
Here is the result after applying the fix :
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1317148/
This fix is only needed for a few Unity versions, but it's working for all of Unity version, so I would advice to …

Bugfix/edges picking not working unity20.2

---

CHANGELOG.md
Editor/MenuActions/Geometry/DetachFaces.cs

The setting for detach to face used to have the option of detaching to a submesh. By design, this didn't refer to the unity definition of a submesh which could be confusing to users. The option is now a toggle for separate gameobject:
**Fogbugz: [case#1315335](https://fogbugz.unity3d.com/f/cases/1315335/)**

Changed the Wording on the Detach Faces Setting

---

CHANGELOG.md
Debug/Editor/Guides.cs
Debug/Editor/Guides.cs.meta
Debug/Editor/Unity.ProBuilder.Debug.Editor.asmdef
Editor/EditorCore/CutTool.cs
Editor/EditorCore/DrawShapeTool.cs
Editor/EditorCore/EditorShapeUtility.cs
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/Experimental.cs
Editor/EditorCore/ProBuilderShapeEditor.cs
Editor/EditorCore/TooltipEditor.cs
Editor/StateMachines/ShapeState_DrawBaseShape.cs
Editor/StateMachines/ShapeState_InitShape.cs
Runtime/Core/MeshUtility.cs
Runtime/Core/ShapeGenerator.cs
Runtime/MeshOperations/MeshTransform.cs
Runtime/Shapes/ProBuilderShape.cs
Tests/Editor/Actions/StripProBuilderScriptsTest.cs
package.json

- Fixed `Draw Shape` tool showing incorrect UVs when setting shape bounding box.
- Fixed `Draw Shape` tool not clearing selection when changing the active shape type.
- Fixed `Cut Tool` error when pressing `Backspace` with no vertices placed.
- Fixed `Cut Tool` error when finishing a cut segment with less than 3 vertices.
- Fixed `Draw Shape` tool truncating shape property fields in the Scene View Overlay.
- Moved contents of warning box in `Draw Shape` tool to tooltips.

Bugfixes 5x release

---

package.json

Re-adding the package description changes for SRP support that were introduced in an earlier PR. The description change informs SRP users that the appropriate ProBuilder Samples should be imported for full functionality.
FogBugz ticket - https://fogbugz.unity3d.com/f/cases/1304442/
Previous PR - https://github.com/Unity-Technologies/com.unity.probuilder/pull/363

Package description update for SRP support

---

CHANGELOG.md
Runtime/Core/ProBuilderMeshFunction.cs
Runtime/Core/Submesh.cs

Preventing creation of empty submeshes when probuilderizing meshes with multiple materials but no submeshes.
https://fogbugz.unity3d.com/f/cases/1320936/

Preventing creation of empty submeshes when probuilderizing 

---

CHANGELOG.md
Runtime/Shapes/Sphere.cs
Runtime/Shapes/Torus.cs

This PR fixes a problem in UV generation for the New Shape tool for Spheres and Torus shapes.
The PR corrects that by using the same projection parameters that were used for PB4.4
Previous UVs:
New UVs:
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1322150/

Fixing sphere and torus UV generation

---

CHANGELOG.md
Runtime/Core/ProBuilderMesh.cs

Fixing Gen Shadow Obj tool from ProBuilder window.
The problem was due to a bad initialization of ProBuilderMesh colors table on domain reload.
In the case were colors table is null, this would result in a table of 0 elements on domain reload and create the current problem with a count difference between the vertex and the color count.
Preventing this by settings colors table to null if no elements are in the table.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1322032/

Fixing 'Gen Shadow Obj' tool from ProBuilder window

---

CHANGELOG.md
Runtime/Core/ProBuilderMeshFunction.cs

Using Unity 21.2 a new error message appear wile drawing the shape:
This is actually caused when trying to assign a mesh that doesn't have any vertex to the meshcollider.
This is fixed in this PR by just checking that vertexCount > 0 before assigning it to the collider and assigning a null mesh if it's the case.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1323666/

Bugfix/fixing mesh collider error with unity21.2

---

Editor/EditorCore/EditShapeTool.cs
Editor/EditorCore/ProBuilderEditor.cs

Fix for PB EditShape Tool.
When using PB5 with Unity 20.2 and after (use of EditorToolContext) using the EditShapeTool does not allow to start New Shape or New Polyshape tools and automatically returns to 
The PR fixes that.
EditShapeTool bug:

EditShapeTool bugfix

---

CHANGELOG.md
Editor/EditorCore/UnityScenePostProcessor.cs

Building scenes with prefabs was causing errors in the console during script scripting. This was due to the use of FindObjectsOfTypeAll introduced previously to strip scripts on objects that were disabled in the scene. As this function also retrieves prefabs, this PR checks if the actual object is a prefab or an instantiated object before stripping. 
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1324399/

Fixing errors popping in console when building scenes with prefabs

---

CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs
package.json
validationExceptions.json
validationExceptions.json.meta

This PR fixes an issue where some Gizmos Menu items would be missing in projects that have the ProBuilder package installed.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1332226
Sequence of events causing this issue:
- User selects to install PB package or opens a project that contains PB
- Domain reload is triggered
- `GizmoSetup` (C++) receives `OnBeforeDomainReload` and clears all gizmo renderers and setups
- `AnnotationManager` (C++) receives `OnDomainReload` and sets its dirty flag
- `[InitializeOnLoad]` attributes are processed and PB `HierarchyListener`'s constructor is called which in turn calls `AnnotationUtility.GetAnnotations()`
- `AnnotationManager.GetAnotations()` internally calls `AnnotationManager.Refresh()` which, due to the dirty flag being set previously, attempts to …

Fix for missing Gizmos Menu items for projects that have ProBuilder installed

---

CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs

Backport of this PR: https://github.com/Unity-Technologies/com.unity.probuilder/pull/392
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1332226

[Backport] Fix for missing Gizmos Menu items for projects that have ProBuilder installed

---

Addons/Fbx.cs
Addons/Unity.ProBuilder.AddOns.Editor.asmdef
CHANGELOG.md

Fixing Probuilder mesh throwing errors with FBX Exporter due to the presence of ProBuilderShape that was not removed.
The PR calls the `StripProBuilderScripts` class now for more consistency and the code is now also aware of the difference between "FBX Export" that does not replace the PB Object and "Convert to prefab" that creates a prefab, strips PB objects and replace the object in the scene.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1334017/

Fixing PBShape export using FBX Exporter

---

CHANGELOG.md
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/ShapeEditor.cs
Editor/EditorCore/VertexManipulationTool.cs
package.json

- Fixed exception when using vertex snapping in Unity 2019.4 and newer.
- Fixed API Updater warning when opening in Unity 2021 and newer.

fix unecessary reflection to get nearest vertex

---

CHANGELOG.md
Editor/EditorCore/VertexManipulationTool.cs
Tests/Editor/Geometry/VertexManipulationTests.cs
Tests/Editor/Geometry/VertexManipulationTests.cs.meta

This PR fixes an issue where performing an element extrusion that is orthogonal to the element's normal would result in that element being additionally extruded along its normal by 0.0001. 
Added new test.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1368465/

Fixed orthogonal element extrusions resulting in slight offset along normal

---

.yamato/promotion.yml
.yamato/upm-ci.yml

Updating Unity versions for editor tests;
Removing 2020.1 and 2020.2
Adding 2020.3 (LTS), 2021.2 (LTS) and 2022.1

Updating Unity versions for editor tests

---

CHANGELOG.md
Editor/EditorCore/MenuOption.cs

Removing old reflection now causing Editor crashes on Mac.
The comment was saying:
"don't let window hang around after a script reload nukes the pb_MenuAction instances"
However, this is now handled on domain reload by a delayed call to : `EditorApplication.delayCall += CloseAll;` 
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1395936/

Removing old reflection calls

---

CHANGELOG.md
Editor/MenuActions/Geometry/DetachFaces.cs
Tests/Editor/Undo/TestUndo.cs

Fixes a bug where undoing after a "Detach faces" operation with the "Separate GameObject" option on would not restore the detached faces - leaving the mesh with missing faces. Behaviour before:
Behaviour after:
The issue was that the call to `Undo.RegisterCreatedObjectUndo(copy.gameObject, "Detach Selection");` was issued too early without giving the chance for the prior call to  `UndoUtility.RecordSelection("Detach Face(s)");` to register original mesh's face changes.
Tested with small meshes and meshes with >512 vert count as `UndoUtility.RecordSelection` takes different code paths depending on vertex count. In each case, fix worked correctly.
Added automated test.
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1407518/
[List known …

Fix for Detach Faces undo issue

---

CHANGELOG.md
Editor/EditorCore/MeshSelection.cs

Fixed issue where ProBuilderize action would not Redo properly and would lead to a state where the selected GO would have a `ProBuilderMesh` component but `MeshSelection.topInternal` selection would be empty. Effectively this would result in the ProBuilder window being in a state as if the GO did not have `ProBuilderMesh` component added.
**Jira:** https://jira.unity3d.com/browse/PBLD-8

[Backport 4.5] Fixed ProBuilderize redo issue 

---

Documentation~/api.md

On the **About the ProBuilder Scripting API** page, the example code in the **Modify a Mesh** section is incorrect. The `MeshUtility.CollapseSharedVertices(quad);` won't work as written. The function requires a `UnityEngine.Mesh` and the example uses a `UnityEngine.ProBuilder.ProBuilderMesh`. This was reported in FogBugz 1429897. 
I consulted with @karl- for these changes. 
**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1429897/

FogBugz 1429897: Fix MeshUtility.CollapseSharedVertices(quad) example in api.md

---

CHANGELOG.md
Editor/EditorCore/UnityScenePostProcessor.cs
Runtime/Core/ColliderBehaviour.cs
Runtime/Core/TriggerBehaviour.cs

Backport of https://github.com/Unity-Technologies/com.unity.probuilder/pull/425
Fixes an issue where adding and then subsequently removing a Collider or Trigger entity behaviour would have the side effect of PB mesh no longer rendering in builds. The cause of the issue was the fact that these behaviours would set the renderer's hide flags to `DontSaveInBuild` on Initialize but would not restore it to `None` on removal. 
The user's scene attached to the bug report had a number of PB meshes that did not have the behaviours attached but the renderers had their hideFlags set to `DontSaveInBuild`.
**Jira:** https://jira.unity3d.com/browse/PBLD-10

[Backport 4.5] Fixed Collider/Trigger entity behaviours causing meshes to not render in builds

---

CHANGELOG.md
Content/Shader/FacePicker.shader
Runtime/Core/SelectionPickerRendererStandard.cs

This PR fixes URP support in the Game View in the `SelectionPickerRendererStandard` file.
I also removed the `_Tint` variable from the `FacePicker` shader since it wasn't used.
**Jira:** https://jira.unity3d.com/browse/PBLD-15

Fix URP support in GameView

---

CHANGELOG.md
Editor/StateMachines/ShapeState_DrawHeightShape.cs
package.json

This PR fixes an issue that happened when creating a shape with the camera perspective set to Top. Multiple errors were thrown when setting the height of the newly created shape.
This PR also removes a few duplicate properties in the `package.json` file.
**Jira:** 
- https://jira.unity3d.com/browse/PBLD-19 (Bug) 
- https://jira.unity3d.com/browse/PBLD-21 (Port)

Fixed shape creation when the camera perspective is set to Top (PBLD-19)

---

CHANGELOG.md
Editor/StateMachines/ShapeState_InitShape.cs

Fixing a bug where the RMB is setting the original position of the shape when using the Shape tool although only the LMB should be the correct one.
**Jira:** https://jira.unity3d.com/browse/PBLD-32

Fixing RMB behavior with Shape Tool

---

Documentation~/index.md

Repeated user-generated bugs suggest some users cannot find the Installing ProBuilder link in the sidebar. I added another link to the installation steps to the About ProBuilder page to assist these users. A lot of packages include installation steps on the first page of the package's documentation, so this change will bring ProBuilder more in line with what user's expectations might be.
**Fogbugz:**
**Jira:** https://jira.unity3d.com/browse/DOCATT-346

DOCATT-346: Added Installing ProBuilder link to index.md

---

CHANGELOG.md
Editor/EditorCore/ScriptingSymbolManager.cs

Fixed a bug where `Experimental Features Enabled` was not activating  when using `Dedicated Server` platform.
Basically the user was clicking on "Experimental Features Enabled" and nothing was happening.
After investigation, he is using the Dedicated server as a platform. The problem is coming from the fact that this platform as not been added in the `BuildTargetGroup` enum and thus was not impacted by the Settings adding the Scripting Define Symbol as this symbol was not added for that specific target.
Moreover the Symbols were set by ProBuilder using `PlayerSettings.[Get/Set]ScriptingDefineSymbolsForGroup` which have been deprecated since. This PR update this as well for Unity 2021.2 and after where `PlayerSettings.[Get/Set]ScriptingDefineSymbols` have been introduced.
This is now …

Fixed a bug where `Experimental Features Enabled` was not activating 

---

CHANGELOG.md
Editor/EditorCore/ScriptingSymbolManager.cs
package.json

Fixed a bug where Experimental Features Enabled was not activating when using Dedicated Server platform.
Basically the user was clicking on "Experimental Features Enabled" and nothing was happening.
After investigation, he is using the Dedicated server as a platform. The problem is coming from the fact that this platform as not been added in the BuildTargetGroup enum and thus was not impacted by the Settings adding the Scripting Define Symbol as this symbol was not added for that specific target.
Moreover the Symbols were set by ProBuilder using PlayerSettings.[Get/Set]ScriptingDefineSymbolsForGroup which have been deprecated since. This PR update this as well for Unity 2021.2 and after where PlayerSettings.[Get/Set]ScriptingDefineSymbols have been introduced.
This is now getting the …

[Backport] Fixed a bug where Experimental Features Enabled was not activating

---

CHANGELOG.md
Editor/EditorCore/EditorMeshUtility.cs

PR fixes an issue where the UV distribution metric was not recalculated after rebuilding a mesh. This would have the side effect of incorrect mip maps being loaded.
Tested for possible performance implications: used a 5k vertex cube and sampled the `EditorMeshUtility. Optimize` function. With `RecalculateUVDistributionMetric` or without  the measurements fluctuated between 55ms and 70ms, therefore if there is any impact, it's pretty negligible and probably around additional 5-10ms per 5K vertices.
**Jira:** https://jira.unity3d.com/browse/PBLD-41
**Slack:** https://unity.slack.com/archives/C7HJDB0A0/p1666627588183009

Fix for no UV distribution metric recalculation after mesh optimization step

---

CHANGELOG.md
Editor/EditorCore/EditShapeTool.cs
Editor/EditorCore/ProBuilderToolManager.cs

PR fixes an issue where activating the Edit Shape tool would prevent the next editor tool context from properly activating. 
**Jira:** https://jira.unity3d.com/browse/PBLD-43

Fixed Edit Shape tool preventing correct activation of next context

---

CHANGELOG.md
Editor/EditorCore/DrawShapeTool.cs
Editor/StateMachines/ShapeState_DrawBaseShape.cs

Fixed a bug where the minimum size for a shape was not taking into account the snap and grid sizes.
The min size was hard coded and not taking the snapping or grid sizes into account, which it does now if these sizes are smaller than the default one (0.1f);
Before:
After:
**Jira:** https://jira.unity3d.com/browse/UUM-19007

[PBLD-48] Change Shape's min size

---

Runtime/Core/ProBuilderMesh.cs

Serialized field m_Mesh is modified on MonoBehaviour awake directly and in some instances prefabs were not being made aware of the change causing non-deterministic build behavior.
Fixes an issue with non-deterministic build behaviour with older versions of ProBuilder components in prefabs in scenes. Here's the behavior noticed:
- ProBuilderMesh.cs in prior versions did not serialized out m_Mesh field.
- This scene has a prefab instance from that older version.
- This causes the mesh to be recreated every time.
- Reserializing out the scene does not cause the prefab instance to add that missing property modification.
So as a result the mesh will always be recreated every time as this field is not being picked up as a property modification …

Fix bug with prefabs not tracking serialized mesh

---

CHANGELOG.md
Editor/EditorCore/DrawShapeTool.cs
Runtime/Shapes/ProBuilderShape.cs

This main part of the bug (console errors) has been fixed between 5.0.6 and .7 but there was still some remaining problems, like the shape being not in the right place or the values set in the ProBuilderShape size field.
**Jira:** https://jira.unity3d.com/browse/PBLD-62

Fxing errors and bad size shape when trying to draw a 0-size shape

---

CHANGELOG.md
Runtime/Shapes/Stairs.cs

Fixes the `Stair` shape not copying the `Inner Radius` value from prefs.
**Jira:** https://jira.unity3d.com/browse/PBLD-65

fix missing inner radius field in stairs pref

---

CHANGELOG.md
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/ProBuilderMeshPreview.cs
Editor/EditorCore/StripProBuilderScripts.cs
Tests/Editor/Actions/StripProBuilderScriptsTest.cs

Create assets in the project when "Strip ProBuilder Scripts" is used, preventing an issue where prefabs would reference scene assets.
**Fogbugz:**
**Jira:** https://jira.unity3d.com/browse/PBLD-63

fix missing mesh reference in prefabs after stripping probuilder mesh

---

CHANGELOG.md
Editor/EditorCore/BezierSplineEditor.cs
Editor/EditorCore/StripProBuilderScripts.cs

Fixed an issue where "Strip ProBuilder Scripts" in a prefab stage would not persist. Additionally, corrected the mesh asset collection logic in the "strip all" option to consider only active scenes with respect to the current stage.
**Fogbugz:**
**Jira:** https://jira.unity3d.com/browse/PBLD-64
Skipping a test on this one because the risk of regression is low and the cost of spinning up a test for prefab staging specifically is high.

fix strip probuilder scripts not working in prefab stage

---

.yamato/promotion.yml
.yamato/upm-ci.yml
CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs
Editor/EditorCore/StripProBuilderScripts.cs
Editor/EditorCore/UVEditor.cs
Tests/Editor/Editor/MeshSyncTests.cs
package.json
validationExceptions.json
validationExceptions.json.meta

This reverts commit https://github.com/Unity-Technologies/com.unity.probuilder/commit/d07ed6c7a32a7c1ff661a0b9491dc4d2700ab558.
We can't promote the unity version in package.json since this is a minor release. Reverting commit https://github.com/Unity-Technologies/com.unity.probuilder/commit/d07ed6c7a32a7c1ff661a0b9491dc4d2700ab558 because we need to support tests for 2019.4 (otherwise Yamato blocks).
EDIT 2023-06-08
There are public API changes in this release (MeshSyncState has a new enum entry) and Yamato blocks this from being a minor version update. So bumping to 5.1.0 instead of 5.0.8 now.

Bump version to 5.1.0 and revert test versions back to 2019.4

---

Documentation~/workflow-uvs.md

A user left this feedback on the "Mapping Textures with UVs" page:
> What's a "UV Editor Window"? How do I open it? Or where do I find it? I'm checking my Material, my texture and the model with it, but can't find.
`uv-editor-md` clearly describes how to open this window, so I added some links to this documentation page to address this user's feedback. 
**Jira:** https://jira.unity3d.com/browse/DOCATT-1163

DOCATT-1163: Add links to UV editor to the "Mapping Textures with UVs" documentation

---

CHANGELOG.md
Runtime/Core/ProBuilderMeshFunction.cs

This PR fixes a regression in the poly shape tool, with the user not being able to set an extrusion point, that I caused when fixing these bugs (https://jira.unity3d.com/browse/PBLD-52 and https://jira.unity3d.com/browse/PBLD-70).
**Jira:** https://jira.unity3d.com/browse/PBLD-78

Fix poly shape regression - not being able to set an extrusion point.

---

Documentation~/api.md
Documentation~/vertex-colors.md

* Fixed broken link in `vertex-colors.md`.
* In `api.md`, changed the `Modify a Mesh` sample. It was no longer compiling. 
**Jira:**
- https://jira.unity3d.com/browse/DOCATT-381
- https://jira.unity3d.com/browse/DOCATT-392
- https://jira.unity3d.com/browse/DOCATT-404
- https://jira.unity3d.com/browse/DOCATT-410
- https://jira.unity3d.com/browse/DOCATT-1048
- https://jira.unity3d.com/browse/DOCATT-3025

August ProBuilder documentation fixes

---

CHANGELOG.md
Editor/EditorCore/ProBuilderAnalytics.cs

API has been changed in unity 2023.2.0a22 and after for analytics causing warning messages in the console when using ProBuilder. 
This PR updates the analytics to use the new API for 2023.2 and after.
Based on this doc : https://docs.editor-data.unity3d.com/Contribute/EditorAnalytics/cs_guide/
**Jira:** https://jira.unity3d.com/browse/STO-2988

API Update for Analytics

---

CHANGELOG.md
External/CSG/Classes/Plane.cs

Fixed a bug where an infinite recursion loop could crash the editor when using the Boolean tool.
The problem was caused by the creation of a new polygon every single time using:
`{front/back}.Add(new Polygon(f, polygon.material));`
In some cases, the created polygon was slightly different from the original one, causing a stoppin condition to fail in Node.Build  (line 116 or line 124), causing another call to Build() with the same polygin vertices, causing the same issue on the following loop.
`if (newNode && list.SequenceEqual(listBack/Front))`
Checking the vertex equality before creating the polygon fixes that, then the original polygon is used, instead of a new one.
Also adding a small optimization, checking that the new added polygon is valid before adding it to the list.
**Jira:** …

[PBLD-87] Fixing infinite recursion

---

Editor/EditorCore/MenuToolToggle.cs.meta

Removed merge conflict markers (">>>>>>", etc...) as they were causing the following error on CI checks for DOTS monorepo job:
`The GUID inside 'Packages/com.unity.probuilder/Editor/EditorCore/MenuToolToggle.cs.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.`
**Jira:** Part of https://jira.unity3d.com/browse/DOTS-9177

Removed merge conflict markers

---

CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs
Tests/Editor/Editor/MeshSyncTests.cs

Duplicating a parent of a PBMesh was not updating the reference to the Mesh and still pointing to the original mesh.
This PR fixes this and allow to duplicate GameObject with ProBuilderMesh children.
+ Adding tests
**Jira:** https://jira.unity3d.com/browse/PBLD-75

[PBLD-75] Fixing mesh duplication when ProBuilder Mesh is on children object

---

.buginfo

Internal change, no entry to changelog is intentional.
Adds the `package` field to `.buginfo` file.
**Jira:**
https://jira.unity3d.com/browse/CODE-562

add package field to buginfo file

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditor.cs

This PR fixes an issue where it was no longer possible to do mesh editing or enable view tools after the new shortcut improvements were added to the editor.

Fixed the left mouse click for mesh editing not working with the new shortcut improvements.

---

CHANGELOG.md
package.json

Bumping package to 5.2.1 to publish the important fix, otherwise 5.2.0 is not really usable with latest Unity builds (View tool cannot be used anymore)

Package bump : RC 5.2.1

---

CHANGELOG.md
Editor/EditorCore/MainToolbar.cs

Fixed a bug that prevented the ProBuilder window to update its content after changing its docking position.
The problem was caused by the fact that the events when registered in the constructor and unregistered when docking was changed from the original position, and then never registered again.
Moving the event registration to the AttachToPanelEvent event fixes this problem.
**Jira:** https://jira.unity3d.com/browse/PBLD-88

[PBLD-88] Fixing ProBuilder Window not refreshing

---

Debug/Editor/GenerateMenuItems.cs
Debug/Scripts/Teleport.cs
Editor/EditorCore/EditorToolbarMenuItems.cs
Editor/EditorCore/ProBuilderToolsContexts.cs

ProBuilder 6 context menu updates regarding the revert of the current context menu solution.
Trunk API is going to change, so PB6 needs to be updating accordingly before being published.
This work is based on this branch :
`uitools/contextual-menu/revert-feature`
We should wait for that branch to land on trunk before publishing this new package update.
**Jira:** https://jira.unity3d.com/browse/STO-3081

[PB 6] Reverting context menu

---

CHANGELOG.md
Documentation~/filter.yml
Documentation~/projectMetadata.json
package.json

Fixed a documentation generation problem where a setting in the `filter.yml` file was preventing the ProBuilder API documentation from being generated with the newest version of the Package Manager DocTools package (v3.x).  
- Removed the lines to exclude the **Global Namespace** from the `filter.yml` file
- Enabled the `hideGlobalNamespace` setting in the `projectMetadata.json` file instead
**[WEBDOCS-1036](https://jira.unity3d.com/browse/WEBDOCS-1036)**
No changes to code or doc content.
**Note**: The DocTools team republished the 5.2 docs as an exception so the API docs would be available immediately, but in case any more changes will be made I added a Changelog entry and bumped the version. If you prefer, I can remove those changes and just apply the filter changes. I will also need …

Doc fix for 5.2+ to restore api docs

---

Debug/Editor/GenerateMenuItems.cs
Editor/EditorCore/EditorToolbarMenuItems.cs
Editor/MenuActions/Geometry/BevelEdges.cs
Editor/MenuActions/Geometry/CollapseVertices.cs
Editor/MenuActions/Geometry/DetachFaces.cs
Editor/MenuActions/Geometry/DuplicateFaces.cs
Editor/MenuActions/Geometry/ExtrudeEdges.cs
Editor/MenuActions/Geometry/ExtrudeFaces.cs
Editor/MenuActions/Geometry/FillHole.cs
Editor/MenuActions/Geometry/OffsetElements.cs
Editor/MenuActions/Geometry/SubdivideEdges.cs
Editor/MenuActions/Geometry/WeldVertices.cs
Editor/MenuActions/Object/MirrorObjects.cs
Editor/MenuActions/Selection/GrowSelection.cs
Editor/MenuActions/Selection/SelectEdgeLoop.cs
Editor/MenuActions/Selection/SelectEdgeRing.cs
Editor/MenuActions/Selection/SelectFaceLoop.cs
Editor/MenuActions/Selection/SelectMaterial.cs
Editor/MenuActions/Selection/SelectVertexColor.cs
Editor/Overlays/ActionSettings.cs

Regarding last week reviews, the main blocker for PB6 was the preview button, this was also casing inconsistencies between the parameter settings and the applied values...
This PR fixes that by improving live preview.
Also adding a parameter in case of dealing with large meshes and in that case only updating preview on mouse release/field edition.
**Jira:**

Preview improvement

---

Documentation~/filter.yml
Documentation~/projectMetadata.json

Backported fix for filtered API docs from `5.2/doc-filter-update` branch
Backported the change from [PR#496](https://github.com/Unity-Technologies/com.unity.probuilder/pull/496) to fix the problem with filtering out the ProBuilder API docs with the newer version of the Package Manager DocTools package (v3.x):
- Removed the lines to exclude the **Global Namespace** from the `filter.yml` file
- Enabled the `hideGlobalNamespace` setting in the `projectMetadata.json` file instead
**[WEBDOCS-1036](https://jira.unity3d.com/browse/WEBDOCS-1036)**
No changes to code or doc content.
I didn't include a changelog entry or patch bump here since this is applied to an unpublished version, but I am happy to do that if you want.

WEBDOCS-1036: Backported fix for filtered API docs

---

CHANGELOG.md
Editor/EditorCore/PolyShapeTool.cs

This PR 
- Prevents the Create Polyshape tool to create 'ghost' game objects in the hierarchy 
- fix a bug where entering the tool with a polyshape already selected wouldn't work
**Jira:** https://jira.unity3d.com/browse/PBLD-113

[PB6] Create PolyShape tool improvement

---

CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs
Tests/Editor/Editor/MeshSyncTests.cs
Tests/Editor/Object/PrefabTests.cs

When modifying a pb mesh in a prefab and applying the ovrerrides, some prefabs where not updated.
This is beccause in that case the versionIndex could be set to 0 and as the ProBuilderMesh.meshSyncState says :
// if the local version index is uninitialized, that means no edits have occurred since loading this
// mesh. it could mean a new mesh was created and ToMesh has not been called yet, or that this mesh was
// copy/pasted from an existing instance.
// in the latter case, it is handled by listening to the ObjectChangeEvent stream in HierarchyListener.
// this function only cares about the case where modifications have been made during the current session.
This is also the case when the mesh is part of a prefab and as not been modified, but it should be updated as well when the instance …

[PBLD-110] Updating prefab instances

---

CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs
Tests/Editor/Editor/MeshSyncTests.cs
Tests/Editor/Object/PrefabTests.cs

[Backport from 6.0.x] https://github.com/Unity-Technologies/com.unity.probuilder/pull/508
When modifying a pb mesh in a prefab and applying the ovrerrides, some prefabs where not updated.
This is beccause in that case the versionIndex could be set to 0 and as the ProBuilderMesh.meshSyncState says :
// if the local version index is uninitialized, that means no edits have occurred since loading this
// mesh. it could mean a new mesh was created and ToMesh has not been called yet, or that this mesh was
// copy/pasted from an existing instance.
// in the latter case, it is handled by listening to the ObjectChangeEvent stream in HierarchyListener.
// this function only cares about the case where modifications have been made during the current session.
This is also the case when the mesh is …

[Backport][PBLD-110] Updating prefab instances

---

CHANGELOG.md
Editor/EditorCore/DrawShapeTool.cs
Editor/EditorCore/EditorToolbarMenuItems.cs
Editor/EditorCore/PolyShapeTool.cs

Changed these ProBuilder menu items so they match their labels in the Scene view: 
- Change `New Bezier Shape` to `Create Bezier Shape` 
- Change `New PolyShape` to `Create PolyShape` 
- Change `New Shape` to `Create Shape`
**Jira:** https://jira.unity3d.com/browse/DOCATT-5791
Have I missed anything?

[DOCATT-5791] Edit Create Shape tools menu labels so they match UI in scene view

---

CHANGELOG.md
Editor/EditorCore/UndoUtility.cs
Runtime/Core/ProBuilderMesh.cs
Runtime/Core/ProBuilderMeshFunction.cs
Tests/Editor/Undo/TestUndo.cs

Removing a NonVersionedEditScope.
This was introduced when the Mesh Version index was not serialized. Now this value is serialized, we need that for the Undo and Redo to work properly.
**Jira:** https://jira.unity3d.com/browse/PBLD-128

[PBLD-129] Fixing redo problem with PB Actions

---

Documentation~/TableOfContents.md
Documentation~/menu-open.md

Remove the ProBuilder Window page, because that window doesn't exist in ProBuilder 6.
https://jira.unity3d.com/browse/DOCATT-5819
Documentation only

Removing menu-open from TOC

---

CHANGELOG.md
Editor/MenuActions/Editors/NewBezierShape.cs
Editor/StateMachines/ShapeState_DrawHeightShape.cs
Tests/Editor/Undo/TestUndo.cs

Purpose of this PR
[PBLD-127] Fixed a bug where undoing a shape creation would reset the deleted shape in the scene.
This was caused by Undo registering done in the wrong order:
UndoUtility.RegisterCreatedObjectUndo should be called BEFORE EditorUtility.InitObject 
(EditorUtility.InitObject is calling ComponentUtility.MoveComponentRelativeToComponent which was calling this problem)
Links
Jira: https://jira.unity3d.com/browse/PBLD-127

[PBLD-127] Fixing undo respawning deleted shapes

---

CHANGELOG.md
Editor/StateMachines/ShapeState_DrawHeightShape.cs

PR fixes an issue where drawing the height during PB shape creation would cause visual glitches on macOS.
**Jira:** https://jira.unity3d.com/browse/PBLD-135

Fixed visual glitches when drawing PB shapes on macOS

---

CHANGELOG.md
Editor/StateMachines/ShapeState_DrawHeightShape.cs

Backport PR fixes an issue where drawing the height during PB shape creation would cause visual glitches on macOS.
**Jira:** https://jira.unity3d.com/browse/PBLD-136

[PB 5.2] Fixed visual glitches when drawing PB shapes on macOS 

---

CHANGELOG.md
Content/Resources/Materials/ProBuilderDefault.mat
Editor/EditorCore/DrawShapeTool.cs
Editor/EditorCore/EditorUtility.cs
Editor/EditorCore/PolyShapeTool.cs
Tests/Editor/Object/CreateDestroy.cs

PR fixes an issue where warnings would be thrown or some parts of PolyShapes would render invisible when Resident Drawer is on.
There's too parts to the fix:
1) `EditorUtility.InitObject` no longer results configurations where there's zero submeshes but one or more materials - this would cause Resident Drawer to throw errors.
2) Material is more aggressively refreshed as otherwise geometry added after setting the material would render as if there's no material set - probably has to do with how Resident Drawer batches geometry.
**Jira:** https://jira.unity3d.com/browse/PBLD-115

Fix PolyShape tool warning when Resident Drawer enabled

---

CHANGELOG.md
Editor/EditorCore/HierarchyListener.cs
Tests/Editor/Editor/MeshSyncTests.cs
Tests/Framework/TestUtility.cs
Tests/Scenes/EmptyScene.unity
Tests/Scenes/EmptyScene.unity.meta

Backport of: https://github.com/Unity-Technologies/com.unity.probuilder/pull/543
**Jira:** https://jira.unity3d.com/browse/PBLD-139

[Backport 5.2] Fixed issue where duplicating pb mesh would dirty all scenes

---

Documentation~/modes.md
Documentation~/tool-options-overlay.md
Documentation~/workflow-edit-smoothing.md

* Added link and lead-in paragraph to Keyboard Shortcuts section of "Edit modes and active contexts"
* Specified Overlay menu overlay instead of Overlay menu (overlayoverlayoverlayoverlay).
* Fixed tip in Smoothing Editor documentation.
**Jira:** https://jira.unity3d.com/browse/DOCATT-6651

Second round of ProBuilder 6 documentation edits

---

CHANGELOG.md
Editor/EditorCore/EditShapeTool.cs

[PBLD-150] Fixed a bug where the orientation handles would not be useful when manipulating a cube shape.
**Jira:** https://jira.unity3d.com/browse/PBLD-150

[PB 5.2] Backport for the orientation handles removal on the cube shape

---

CHANGELOG.md
Editor/EditorCore/ProBuilderToolsContexts.cs
Editor/Overlays/SceneInformationOverlay.cs

Fixed a bug where ProBuilder would prevent classes inheriting from `UnityEditor.Editor` to compile.
**Jira:** https://jira.unity3d.com/browse/PBLD-158

fixing compilation error when inheriting from Editor

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditorShortcuts.cs

Fixes issue where using PB context switch shortcut on a non-PB GameObject would throw. The "Toggle ProBuilder Context" shortcut has been removed so that built-in "Cycle Tool Modes" is used instead.
**Jira:** https://jira.unity3d.com/browse/PBLD-167

Fix PB context switch shortcut throwing an error

---

CHANGELOG.md
Editor/EditorCore/ProBuilderEditorShortcuts.cs

"Edit Vertices/Edges/Faces" shortcuts now automatically enter the ProBuilder context if that's possible. This is part of the 3 step fix where we remove PB's context switch shortcut, add this change and update trunk so that context cycle shortcut include game object context.
**Jira:** https://jira.unity3d.com/browse/PBLD-169

Edit Vert/Edge/Face shortcuts now auto-enter PB context

---

CHANGELOG.md
Editor/EditorCore/EditorHandleUtility.cs
Editor/EditorCore/PolyShapeTool.cs
Editor/StateMachines/ShapeState_DrawBaseShape.cs
Editor/StateMachines/ShapeState_DrawHeightShape.cs

- [STO-3427] Fixing a bug where Polyshape creation tool was not working with orthographic camera.
- [STO-3429] Fixing a bug where increment snapping was ignored when drawing ProBuilder shapes.
- [STO-3432] Fixing a bug where Polyshape creation tool was not placing properly the first point on a custom grids. 
**Jira:**
- [STO-3427]
- [STO-3429]
- [STO-3432]

Various bugfix from Gabe

---

CHANGELOG.md
Editor/MenuActions/Geometry/ExtrudeFaces.cs

PR fixes an issue where selecting any of the `Extrude by` options after hitting `Extrude faces` for a group of faces would always result in `Individual Faces` setting being used under the hood (ignoring the UI selection).
The issue was that the change subscription was done for a `string` argument even when it should have been `System.Enum`. The `System.Enum.Parse` would always fail and return a default value which is `Individual Faces`.
**Jira:** https://jira.unity3d.com/browse/PBLD-183

Fix for 'Extrude by' UI setting having no effect on 'Extrude faces' action

---

CHANGELOG.md
Editor/EditorCore/EditorSceneViewPicker.cs

This PR fixes an issue where hover-highlighted elements were not always selected.
Opened the PR on behalf of @katherinesheridan who temporarily lost access to her GitHub account.
She will take over the PR when she gains back access to her account.
**Jira:** https://jira.unity3d.com/browse/STO-3442

Fixed a bug where hover-highlighted elements are not always selected.

---

Editor/EditorCore/DrawShapeTool.cs
Editor/StateMachines/ShapeState_DrawBaseShape.cs
Editor/StateMachines/ShapeState_DrawHeightShape.cs

PR fixes DrawShapeTool's shift duplication behaviour:
1) Preview not matching the changes in the original shape when Pivot location is being toggled between previews.
2) Duplicated shape always having center as it's pivot location - regardless what the original shape had.
3) Triggering previews between changes to Pivot location sometimes messed up original shape's pivot - it becomes neither pivot nor center.
Before fix:
https://github.com/user-attachments/assets/086690fd-05e3-4cc1-8277-bc95adb28e35
After fix:
https://github.com/user-attachments/assets/dfa33e15-1601-44b5-a788-26e1ba4b74d6
**Jira:** https://jira.unity3d.com/browse/PBLD-185

Fix for DrawShape tool not always respecting pivot location

---

CHANGELOG.md
Editor/EditorCore/DrawShapeTool.cs
Editor/StateMachines/ShapeState_InitShape.cs

[PBLD-187] Fixed an issue where the shape size was incorrect when drawing the shape on an angled surface.
Before fix:
After fix:
Also small performance optimization on the DrawShape tool init phase:
Before:
After:
**Jira:** https://jira.unity3d.com/browse/PBLD-187

[PBLD-187] Fix Drawshape pivot on rotated surfaces

---

CHANGELOG.md
Editor/EditorCore/EditorSceneViewPicker.cs
Editor/EditorCore/UVEditor.cs

Fixed a bug where using the auto-stitch functionality of the UV Editor would not work properly on MacOS.
Adding the 2 following auto-stitch functions to the shortcut manager and removing them from custom code handling:
- Auto-stitch UV
- Copy UV Settings
**Jira:** https://jira.unity3d.com/browse/PBLD-189

[PBLD-189] Fixed auto-stitch shortcuts

---

CHANGELOG.md
Editor/EditorCore/ProbuilderMoveTool.cs
Editor/EditorCore/VertexManipulationTool.cs

This PR fixes the Move tool behavior when using Vertex snapping.
The user now has a setting to activate/de-activate in order to enable vertex snapping on the object itself.
This is a settings in the tool settings toolbar, also assignable using a shortcut.
Leaving that as a settings as using vertex snapping on really complex objects, it might not be desired by users to snap on the object itself :P 
https://jira.unity3d.com/browse/PBLD-192
@gabrielw-us : I would need a new icon for that settings in the toolbar
**Jira:** https://jira.unity3d.com/browse/PBLD-192

[PBLD-192][PB5-Backport] Fix for vertex snapping to self-object vertices

---

CHANGELOG.md
Editor/EditorCore/UVEditor.cs

Fixed a bug where using the auto-stitch functionality of the UV Editor would not work properly on MacOS.
Adding the 2 following auto-stitch functions to the shortcut manager and removing them from custom code handling:
- Auto-stitch UV
- Copy UV Settings
@modrimkus-unity , can you test:
- opening the ScreenshotMenu from the button (I changed UNITY_STANDALON to EDITOR), the menu should now open
- Auto-stich shortcut for MacOS
- CopyUVSettings (Cmd + Shift shortcut should assign the UV of the selected element to the clicked one)
Jira: https://jira.unity3d.com/browse/PBLD-189

[PBLD-189][PB5-Backport] Fixed auto-stitch shortcuts 

---

CHANGELOG.md
Editor/MenuActions/Object/MergeObjects.cs
Tests/Editor/Actions/MergeObjectsTest.cs
Tests/Editor/Actions/MergeObjectsTest.cs.meta

PR fixes issue where merging two or more polyshape objects would not remove the PolyShape component resulting in issue down the line when `Edit PolyShape` tool would be activated.
**Jira:** https://jira.unity3d.com/browse/PBLD-205

Fix for Edit PolyShape tool reverting previously merged polyshapes

---

CHANGELOG.md
Editor/EditorCore/CutTool.cs

This PR fixes an issue where if, while using the Cut Tool, two vertices were placed on the same edge, a null reference exception would be thrown in the console. This was due to the face that the tool was attempting to create a face where it should not.
**Jira:** https://jira.unity3d.com/browse/PBLD-199
None.

[PBLD-199] NullReferenceException when using the Cut Tool

---

CHANGELOG.md
Editor/EditorCore/CutTool.cs

This PR fixes an issue where if, while using the Cut Tool, two vertices were placed on the same edge, a null reference exception would be thrown in the console. This was due to the face that the tool was attempting to create a face where it should not.
**Jira:** https://jira.unity3d.com/browse/PBLD-199
None.

[PBLD-199] [PB 5.2 Backport] NullReferenceException when using the Cut Tool

---

Editor/EditorCore/PolyShapeTool.cs

Some fixes introduced protected apis for public classes - from semantic versioning perspective this is a new API addition. APV: 
```
Information: API Diff - Breaking changes: 0 Additions: 3 Missing Assemblies: 0
Information: {
"assemblyName": "Unity.ProBuilder.Editor",
"additions": [
"MemberAdded ( -> System.Int32 UnityEditor.ProBuilder.PolyShapeTool::m_UndoGroup)",
"MemberAdded ( -> System.Boolean UnityEditor.ProBuilder.PolyShapeTool::isExiting)",
"MemberAdded ( -> System.Void UnityEditor.ProBuilder.PolyShapeTool::HandleKeyEvent(UnityEngine.Event))"
],
```
**Jira:**

Remove protected apis

---

CHANGELOG.md
Runtime/Core/SelectionPickerRendererHDRP.cs

- Corrects behavior of the HDRP selection picker renderer (uses RendererListParams instead of RendererListDesc, and submits the draw command)
**Jira:** https://jira.unity3d.com/browse/PBLD-224

correct behavior of the hdrp selection renderpass

---

CHANGELOG.md
Runtime/Core/ProBuilderMeshFunction.cs
Tests/Editor/Geometry/ProbuilderMeshDegenerateTriangleTest.cs
Tests/Editor/Geometry/ProbuilderMeshDegenerateTriangleTest.cs.meta

This fixes [PBLD-236](https://jira.unity3d.com/browse/PBLD-236) in which degenerate triangles in the output mesh with zero value normals were causing rendering artifacts, especially with bloom in URP.
In the `ProBuilderMesh.ToMesh` method, all the triangles in the mesh are checked to see if they are degenerate, and if they are, they are not added to the output mesh.
This does not remove any vertices that are not used in any faces.
**Jira:**  [PBLD-236](https://jira.unity3d.com/browse/PBLD-236)
A new test has been added - it makes two of the corners of a cube coincident, which prior to this fix would result in a mesh being created with degenerate triangles. It fails if the fix is disabled; passes when it is enabled.

Fixes PBLD-236 degenerate triangles causing rendering issues.

---

CHANGELOG.md
Editor/MenuActions/Object/ProBuilderize.cs
Tests/Editor/Actions/ProBuilderizeActionTest.cs
Tests/Editor/Actions/ProBuilderizeActionTest.cs.meta

- Fixes crash when attempting to probuilderize gameobjects that have isPartOfStaticBatch set to true
**Jira:** https://jira.unity3d.com/browse/PBLD-222
This feature was never supported - The engine doesn't have a way to unset the isPartOfStaticBatch flag, so bypassing these objects is what we can do.

Fix crash when attempting to probuilderize a gameobject that has `isPartOfStaticBatch` set to true.

---

CHANGELOG.md
Editor/EditorCore/MenuAction.cs
Editor/Overlays/ActionSettings.cs
Samples~/Editor/SoftDeleteEdgesAction.cs

[PBLD-238](https://jira.unity3d.com/browse/PBLD-238) details a bug with 'Grow Selection' where your actions between using Grow Selection and the next time you used an action could get undone if you did not explicitly 'Confirm' on the overlay.
As it turns out this bug seems to affect all actions that have a settings dialog with Preview.
The bug also improves the comment on MenuAction.hasFileMenuEntry and its override in the SoftDeleteEdgesAction sample, as the previous comment no longer made sense in the context of ProBuilder 6.
[[https://jira.unity3d.com/browse/PBLD-238]]
So the cause of this bug was tricksy to work out.
Basically, there are a class of actions in ProBuilder that can have different options to them. Grow Selection is one of these, and it has options you can set about …

Fix for PBLD-238 Prevents actions with previews from being undone if you don't press Confirm.

---

AssetIdRemapUtility/Editor/AssetIdRemapBuilderTreeView.cs
AssetIdRemapUtility/Editor/AssetIdRemapEditor.cs
AssetIdRemapUtility/Editor/AssetTreeView.cs
CHANGELOG.md
Editor/EditorCore/EditorMaterialUtility.cs
Editor/EditorCore/HierarchyListener.cs
Editor/EditorCore/ObjExporter.cs

This fixes [PBLD-245](https://jira.unity3d.com/browse/PBLD-245), where loading ProBuilder in to Unity 6.2 or later would result in a lot of warnings related to obsolete API.
The replacements for the obsolete TreeView API and EditorUtility.InstanceIDToObject do not exist prior to Unity 6.2, so in those cases I added pragmas to suppress the warnings. In the case of ShaderUtil.GetProperty___ I replaced the obsolete API calls with the correct ones as they exist as far back as Unity 2021.

Fixes for obsolete API warnings in Unity 6.2.

---

CHANGELOG.md
Runtime/Core/UvAutoManualConversion.cs
Runtime/MeshOperations/UV/TextureStitching.cs
Tests/Editor/UV/AutoStitchingTests.cs
Tests/Editor/UV/AutoStitchingTests.cs.meta

The calculation of the auto stitching was based on the offset between the destination UV center, and the source UV center. This offset is then applied to a face UV. 
The problem with the old calculation, was that when a rotation was needed for a target face, the bounds center could be slightly offseted, when the face was not a rectangle or cube (eg. a trapezoid), since the bounds are calculated using the min,max x and y. This slight offset would result in a misposition of the target face relative to the anchor, which would visually result in an offsetted texture. 
This was solved by making sure we take into account the rotation of the face when calculating the offset.
In the image below, we see that the rotation of the trapezoid modifies its center bound, which is not taken into the …

Fixed a bug with UV autostitching where the position offset would not take into account the face rotation center offset.

---

CHANGELOG.md
Content/Material/Checker.mat
Content/Resources/Materials/ProBuilderDefault.mat

Warnings pop up about materials being altered when one imports the ProBuilder package in Unity 6000.2 and above. This PR serves to update those materials to fix the warnings.
**Jira:**
Tested by importing the local copy of ProBuilder with this fix on the latest versions of Unity 6000.2 and 6000.0

Fix Material Warnings When Importing ProBuilder

---

CHANGELOG.md
Editor/EditorCore/EditorSceneViewPicker.cs
Tests/Editor/Picking/EdgePickerTests.cs

An issue was found with edge selection where even if a specific edge was visually highlighted by the hover system, a different edge might be selected once you left-clicked. This was pretty confusing for users because what they saw highlighted wasn't always what they got when they clicked, making the tool feel a bit unpredictable.
The root of this problem was how the `EdgeRaycast ` function worked. When you clicked, it first cleared any existing selection information. Then, there was a part of the code that checked if an edge was already highlighted. If it was highlighted, the code would skip trying to figure out which game object you were hovering over with `HandleUtility.PickGameObject`. This meant that `selection.gameObject` would stay …

Fixed issue with edge selection.
